INSERT INTO `migrations` VALUES ('20170123105000'); 

INSERT INTO `locales_area` VALUES ('1', '', '', '', '', '', '', '', 'Дун Морог');
INSERT INTO `locales_area` VALUES ('2', '', '', '', '', '', '', '', 'Бескрайний берег');
INSERT INTO `locales_area` VALUES ('3', '', '', '', '', '', '', '', 'Бесплодные земли');
INSERT INTO `locales_area` VALUES ('4', '', '', '', '', '', '', '', 'Выжженные земли');
INSERT INTO `locales_area` VALUES ('7', '', '', '', '', '', '', '', 'Бухта Черноводья');
INSERT INTO `locales_area` VALUES ('8', '', '', '', '', '', '', '', 'Болото Печали');
INSERT INTO `locales_area` VALUES ('9', '', '', '', '', '', '', '', 'Долина Североземья');
INSERT INTO `locales_area` VALUES ('10', '', '', '', '', '', '', '', 'Сумеречный лес');
INSERT INTO `locales_area` VALUES ('11', '', '', '', '', '', '', '', 'Болотина');
INSERT INTO `locales_area` VALUES ('12', '', '', '', '', '', '', '', 'Элвиннский лес');
INSERT INTO `locales_area` VALUES ('13', '', '', '', '', '', '', '', 'Древо Жизни');
INSERT INTO `locales_area` VALUES ('14', '', '', '', '', '', '', '', 'Дуротар');
INSERT INTO `locales_area` VALUES ('15', '', '', '', '', '', '', '', 'Пылевые топи');
INSERT INTO `locales_area` VALUES ('16', '', '', '', '', '', '', '', 'Азшара');
INSERT INTO `locales_area` VALUES ('17', '', '', '', '', '', '', '', 'Степи');
INSERT INTO `locales_area` VALUES ('18', '', '', '', '', '', '', '', 'Озеро Хрустальное');
INSERT INTO `locales_area` VALUES ('19', '', '', '', '', '', '', '', 'Зул\'Гуруб');
INSERT INTO `locales_area` VALUES ('20', '', '', '', '', '', '', '', 'Луноречье');
INSERT INTO `locales_area` VALUES ('21', '', '', '', '', '', '', '', 'Кул-Тирас');
INSERT INTO `locales_area` VALUES ('22', '', '', '', '', '', '', '', 'Остров Программиста');
INSERT INTO `locales_area` VALUES ('23', '', '', '', '', '', '', '', 'Река Североземья');
INSERT INTO `locales_area` VALUES ('24', '', '', '', '', '', '', '', 'Аббатство Североземья');
INSERT INTO `locales_area` VALUES ('25', '', '', '', '', '', '', '', 'Черная гора');
INSERT INTO `locales_area` VALUES ('26', '', '', '', '', '', '', '', 'Маяк');
INSERT INTO `locales_area` VALUES ('28', '', '', '', '', '', '', '', 'Западные Чумные земли');
INSERT INTO `locales_area` VALUES ('30', '', '', '', '', '', '', '', 'Девять');
INSERT INTO `locales_area` VALUES ('32', '', '', '', '', '', '', '', 'Кладбище');
INSERT INTO `locales_area` VALUES ('33', '', '', '', '', '', '', '', 'Тернистая долина');
INSERT INTO `locales_area` VALUES ('34', '', '', '', '', '', '', '', 'Рудник Горного Эха');
INSERT INTO `locales_area` VALUES ('35', '', '', '', '', '', '', '', 'Пиратская Бухта');
INSERT INTO `locales_area` VALUES ('36', '', '', '', '', '', '', '', 'Альтеракские горы');
INSERT INTO `locales_area` VALUES ('37', '', '', '', '', '', '', '', 'Озеро Назферити');
INSERT INTO `locales_area` VALUES ('38', '', '', '', '', '', '', '', 'Лок Модан');
INSERT INTO `locales_area` VALUES ('40', '', '', '', '', '', '', '', 'Западный Край');
INSERT INTO `locales_area` VALUES ('41', '', '', '', '', '', '', '', 'Перевал Мертвого Ветра');
INSERT INTO `locales_area` VALUES ('42', '', '', '', '', '', '', '', 'Темнолесье');
INSERT INTO `locales_area` VALUES ('43', '', '', '', '', '', '', '', 'Пустынный берег');
INSERT INTO `locales_area` VALUES ('44', '', '', '', '', '', '', '', 'Красногорье');
INSERT INTO `locales_area` VALUES ('45', '', '', '', '', '', '', '', 'Нагорье Арати');
INSERT INTO `locales_area` VALUES ('46', '', '', '', '', '', '', '', 'Пылающие степи');
INSERT INTO `locales_area` VALUES ('47', '', '', '', '', '', '', '', 'Внутренние земли');
INSERT INTO `locales_area` VALUES ('49', '', '', '', '', '', '', '', 'Нора Мертвеца');
INSERT INTO `locales_area` VALUES ('51', '', '', '', '', '', '', '', 'Тлеющее ущелье');
INSERT INTO `locales_area` VALUES ('53', '', '', '', '', '', '', '', 'Воровской лагерь');
INSERT INTO `locales_area` VALUES ('54', '', '', '', '', '', '', '', 'Яшмовая шахта');
INSERT INTO `locales_area` VALUES ('55', '', '', '', '', '', '', '', 'Аллея Героев НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('56', '', '', '', '', '', '', '', 'Часовые Вечности');
INSERT INTO `locales_area` VALUES ('57', '', '', '', '', '', '', '', 'Рудник Подземных Глубин');
INSERT INTO `locales_area` VALUES ('59', '', '', '', '', '', '', '', 'Виноградники Североземья');
INSERT INTO `locales_area` VALUES ('60', '', '', '', '', '', '', '', 'Лесная опушка');
INSERT INTO `locales_area` VALUES ('61', '', '', '', '', '', '', '', 'Ревущий водопад');
INSERT INTO `locales_area` VALUES ('62', '', '', '', '', '', '', '', 'Тыквенное поле Бреквеллов');
INSERT INTO `locales_area` VALUES ('63', '', '', '', '', '', '', '', 'Ферма Стоунфилдов');
INSERT INTO `locales_area` VALUES ('64', '', '', '', '', '', '', '', 'Виноградники Маклура');
INSERT INTO `locales_area` VALUES ('65', '', '', '', '', '', '', '', '***Используй меня повторно 3***');
INSERT INTO `locales_area` VALUES ('66', '', '', '', '', '', '', '', '***Используй меня повторно 6***');
INSERT INTO `locales_area` VALUES ('67', '', '', '', '', '', '', '', '***Используй меня повторно 5***');
INSERT INTO `locales_area` VALUES ('68', '', '', '', '', '', '', '', 'Озеро Безмолвия');
INSERT INTO `locales_area` VALUES ('69', '', '', '', '', '', '', '', 'Приозерье');
INSERT INTO `locales_area` VALUES ('70', '', '', '', '', '', '', '', 'Крепость Каменной Стражи');
INSERT INTO `locales_area` VALUES ('71', '', '', '', '', '', '', '', 'Водопад Каменной Стражи');
INSERT INTO `locales_area` VALUES ('72', '', '', '', '', '', '', '', 'Темный портал');
INSERT INTO `locales_area` VALUES ('73', '', '', '', '', '', '', '', 'Гниющий шрам');
INSERT INTO `locales_area` VALUES ('74', '', '', '', '', '', '', '', 'Озеро Слез');
INSERT INTO `locales_area` VALUES ('75', '', '', '', '', '', '', '', 'Каменор');
INSERT INTO `locales_area` VALUES ('76', '', '', '', '', '', '', '', 'Болотное пристанище');
INSERT INTO `locales_area` VALUES ('77', '', '', '', '', '', '', '', 'Старая Наковальня');
INSERT INTO `locales_area` VALUES ('80', '', '', '', '', '', '', '', 'Горы Штормграда');
INSERT INTO `locales_area` VALUES ('81', '', '', '', '', '', '', '', 'Джефф СВ Измененный квадрант');
INSERT INTO `locales_area` VALUES ('82', '', '', '', '', '', '', '', 'Джефф СЗ Квадрант');
INSERT INTO `locales_area` VALUES ('83', '', '', '', '', '', '', '', 'Джефф ЮВ Квадрант');
INSERT INTO `locales_area` VALUES ('84', '', '', '', '', '', '', '', 'Джефф ЮЗ Квадрант');
INSERT INTO `locales_area` VALUES ('85', '', '', '', '', '', '', '', 'Тирисфальские леса');
INSERT INTO `locales_area` VALUES ('86', '', '', '', '', '', '', '', 'Озеро Каменных Столбов');
INSERT INTO `locales_area` VALUES ('87', '', '', '', '', '', '', '', 'Златоземье');
INSERT INTO `locales_area` VALUES ('88', '', '', '', '', '', '', '', 'Лесопилка Восточной долины');
INSERT INTO `locales_area` VALUES ('89', '', '', '', '', '', '', '', 'Сад у Зеркального озера');
INSERT INTO `locales_area` VALUES ('91', '', '', '', '', '', '', '', 'Башня Азоры');
INSERT INTO `locales_area` VALUES ('92', '', '', '', '', '', '', '', 'Зеркальное озеро');
INSERT INTO `locales_area` VALUES ('93', '', '', '', '', '', '', '', 'Лощина Вул\'Гол');
INSERT INTO `locales_area` VALUES ('94', '', '', '', '', '', '', '', 'Вороний Холм');
INSERT INTO `locales_area` VALUES ('95', '', '', '', '', '', '', '', 'Каньоны Красногорья');
INSERT INTO `locales_area` VALUES ('96', '', '', '', '', '', '', '', 'Башня Илгалара');
INSERT INTO `locales_area` VALUES ('97', '', '', '', '', '', '', '', 'Лесопилка Альтера');
INSERT INTO `locales_area` VALUES ('98', '', '', '', '', '', '', '', 'Пещеры Ретбана');
INSERT INTO `locales_area` VALUES ('99', '', '', '', '', '', '', '', 'Лагерь Повстанцев');
INSERT INTO `locales_area` VALUES ('100', '', '', '', '', '', '', '', 'Экспедиция Эрнестуэя');
INSERT INTO `locales_area` VALUES ('101', '', '', '', '', '', '', '', 'Лагерь Курцена');
INSERT INTO `locales_area` VALUES ('102', '', '', '', '', '', '', '', 'Руины Зул\'Кунды');
INSERT INTO `locales_area` VALUES ('103', '', '', '', '', '', '', '', 'Руины Зул\'Мамве');
INSERT INTO `locales_area` VALUES ('104', '', '', '', '', '', '', '', 'Коварный риф');
INSERT INTO `locales_area` VALUES ('105', '', '', '', '', '', '', '', 'Холм Мош\'Огг');
INSERT INTO `locales_area` VALUES ('106', '', '', '', '', '', '', '', 'Схрон');
INSERT INTO `locales_area` VALUES ('107', '', '', '', '', '', '', '', 'Ферма Сальдена');
INSERT INTO `locales_area` VALUES ('108', '', '', '', '', '', '', '', 'Сторожевой холм');
INSERT INTO `locales_area` VALUES ('109', '', '', '', '', '', '', '', 'Тыквенная ферма Хмуроброва');
INSERT INTO `locales_area` VALUES ('111', '', '', '', '', '', '', '', 'Рудник Янго');
INSERT INTO `locales_area` VALUES ('113', '', '', '', '', '', '', '', 'Прииск на Золотом Берегу');
INSERT INTO `locales_area` VALUES ('115', '', '', '', '', '', '', '', 'Маяк в Западном Крае');
INSERT INTO `locales_area` VALUES ('116', '', '', '', '', '', '', '', 'Туманная долина');
INSERT INTO `locales_area` VALUES ('117', '', '', '', '', '', '', '', 'Лагерь Гром\'гол');
INSERT INTO `locales_area` VALUES ('118', '', '', '', '', '', '', '', 'Раскопки Вельгара');
INSERT INTO `locales_area` VALUES ('120', '', '', '', '', '', '', '', 'Гарнизон у Западного ручья');
INSERT INTO `locales_area` VALUES ('121', '', '', '', '', '', '', '', 'Безмятежное кладбище');
INSERT INTO `locales_area` VALUES ('122', '', '', '', '', '', '', '', 'Руины Зуулдая');
INSERT INTO `locales_area` VALUES ('123', '', '', '', '', '', '', '', 'Руины Бал\'лал');
INSERT INTO `locales_area` VALUES ('125', '', '', '', '', '', '', '', 'Руины Кал\'аи');
INSERT INTO `locales_area` VALUES ('126', '', '', '', '', '', '', '', 'Руины Ткаши');
INSERT INTO `locales_area` VALUES ('127', '', '', '', '', '', '', '', 'Руины Балиа\'ма');
INSERT INTO `locales_area` VALUES ('128', '', '', '', '', '', '', '', 'Руины Зиата\'джаи');
INSERT INTO `locales_area` VALUES ('129', '', '', '', '', '', '', '', 'Руины Мизжа');
INSERT INTO `locales_area` VALUES ('130', '', '', '', '', '', '', '', 'Серебряный бор');
INSERT INTO `locales_area` VALUES ('131', '', '', '', '', '', '', '', 'Каранос');
INSERT INTO `locales_area` VALUES ('132', '', '', '', '', '', '', '', 'Холодная долина');
INSERT INTO `locales_area` VALUES ('133', '', '', '', '', '', '', '', 'Гномреган');
INSERT INTO `locales_area` VALUES ('134', '', '', '', '', '', '', '', 'Карьер Гол\'Болар');
INSERT INTO `locales_area` VALUES ('135', '', '', '', '', '', '', '', 'Форт Мерзлогривов');
INSERT INTO `locales_area` VALUES ('136', '', '', '', '', '', '', '', 'Серая берлога');
INSERT INTO `locales_area` VALUES ('137', '', '', '', '', '', '', '', 'Поселок Пивоваров');
INSERT INTO `locales_area` VALUES ('138', '', '', '', '', '', '', '', 'Сторожка у заснеженной сосны');
INSERT INTO `locales_area` VALUES ('139', '', '', '', '', '', '', '', 'Восточные Чумные земли');
INSERT INTO `locales_area` VALUES ('141', '', '', '', '', '', '', '', 'Тельдрассил');
INSERT INTO `locales_area` VALUES ('142', '', '', '', '', '', '', '', 'Раскопки Сталекрута');
INSERT INTO `locales_area` VALUES ('143', '', '', '', '', '', '', '', 'Оплот Мо\'грош');
INSERT INTO `locales_area` VALUES ('144', '', '', '', '', '', '', '', 'Телcамар');
INSERT INTO `locales_area` VALUES ('145', '', '', '', '', '', '', '', 'Врата Альгаза');
INSERT INTO `locales_area` VALUES ('146', '', '', '', '', '', '', '', 'Каменная Плотина');
INSERT INTO `locales_area` VALUES ('147', '', '', '', '', '', '', '', 'Приют Странников');
INSERT INTO `locales_area` VALUES ('148', '', '', '', '', '', '', '', 'Темные берега');
INSERT INTO `locales_area` VALUES ('149', '', '', '', '', '', '', '', 'Рудник у Серебряного ручейка');
INSERT INTO `locales_area` VALUES ('150', '', '', '', '', '', '', '', 'Гавань Менетилов');
INSERT INTO `locales_area` VALUES ('151', '', '', '', '', '', '', '', 'Остров Дизайнера');
INSERT INTO `locales_area` VALUES ('152', '', '', '', '', '', '', '', 'Бастион');
INSERT INTO `locales_area` VALUES ('153', '', '', '', '', '', '', '', 'Руины Лордерона');
INSERT INTO `locales_area` VALUES ('154', '', '', '', '', '', '', '', 'Могильник');
INSERT INTO `locales_area` VALUES ('155', '', '', '', '', '', '', '', 'Паучья низина');
INSERT INTO `locales_area` VALUES ('156', '', '', '', '', '', '', '', 'Усадьба Соллиден');
INSERT INTO `locales_area` VALUES ('157', '', '', '', '', '', '', '', 'Мельницы Агамондов');
INSERT INTO `locales_area` VALUES ('158', '', '', '', '', '', '', '', 'Семейная усыпальница Агамондов');
INSERT INTO `locales_area` VALUES ('159', '', '', '', '', '', '', '', 'Брилл');
INSERT INTO `locales_area` VALUES ('160', '', '', '', '', '', '', '', 'Шепчущие сады');
INSERT INTO `locales_area` VALUES ('161', '', '', '', '', '', '', '', 'Терраса Покоя');
INSERT INTO `locales_area` VALUES ('162', '', '', '', '', '', '', '', 'Озеро Ясноводное');
INSERT INTO `locales_area` VALUES ('163', '', '', '', '', '', '', '', 'Приют Гюнтера');
INSERT INTO `locales_area` VALUES ('164', '', '', '', '', '', '', '', 'Ферма Гаррена');
INSERT INTO `locales_area` VALUES ('165', '', '', '', '', '', '', '', 'Усадьба Балнира');
INSERT INTO `locales_area` VALUES ('166', '', '', '', '', '', '', '', 'Поместье \"Остывший Очаг\"');
INSERT INTO `locales_area` VALUES ('167', '', '', '', '', '', '', '', 'Застава Алого Ордена');
INSERT INTO `locales_area` VALUES ('168', '', '', '', '', '', '', '', 'Северное побережье');
INSERT INTO `locales_area` VALUES ('169', '', '', '', '', '', '', '', 'Шепчущий берег');
INSERT INTO `locales_area` VALUES ('170', '', '', '', '', '', '', '', 'Озеро Лордамер');
INSERT INTO `locales_area` VALUES ('172', '', '', '', '', '', '', '', 'Остров Фенриса');
INSERT INTO `locales_area` VALUES ('173', '', '', '', '', '', '', '', 'Могила Фаола');
INSERT INTO `locales_area` VALUES ('186', '', '', '', '', '', '', '', 'Доланаар');
INSERT INTO `locales_area` VALUES ('187', '', '', '', '', '', '', '', 'Дарнас НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('188', '', '', '', '', '', '', '', 'Тенистая долина');
INSERT INTO `locales_area` VALUES ('189', '', '', '', '', '', '', '', 'Поселок Сталежара');
INSERT INTO `locales_area` VALUES ('190', '', '', '', '', '', '', '', 'Дольный Очаг');
INSERT INTO `locales_area` VALUES ('192', '', '', '', '', '', '', '', 'Лесопилка Северного Кряжа');
INSERT INTO `locales_area` VALUES ('193', '', '', '', '', '', '', '', 'Руины Андорала');
INSERT INTO `locales_area` VALUES ('195', '', '', '', '', '', '', '', 'Школа некромантии');
INSERT INTO `locales_area` VALUES ('196', '', '', '', '', '', '', '', 'Гробница Утера');
INSERT INTO `locales_area` VALUES ('197', '', '', '', '', '', '', '', 'Холм Печали');
INSERT INTO `locales_area` VALUES ('198', '', '', '', '', '', '', '', 'Грот Слез');
INSERT INTO `locales_area` VALUES ('199', '', '', '', '', '', '', '', 'Поле Джанис');
INSERT INTO `locales_area` VALUES ('200', '', '', '', '', '', '', '', 'Слезы Далсона');
INSERT INTO `locales_area` VALUES ('201', '', '', '', '', '', '', '', 'Пустошь Гаррона');
INSERT INTO `locales_area` VALUES ('202', '', '', '', '', '', '', '', 'Удел Страданий');
INSERT INTO `locales_area` VALUES ('203', '', '', '', '', '', '', '', 'Крепость Марденхольд');
INSERT INTO `locales_area` VALUES ('204', '', '', '', '', '', '', '', 'Деревня Погребальных Костров');
INSERT INTO `locales_area` VALUES ('205', '', '', '', '', '', '', '', 'Дун Модр');
INSERT INTO `locales_area` VALUES ('206', '', '', '', '', '', '', '', 'Западный Край');
INSERT INTO `locales_area` VALUES ('207', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('208', '', '', '', '', '', '', '', 'Не используется Потайная бухта');
INSERT INTO `locales_area` VALUES ('209', '', '', '', '', '', '', '', 'Крепость Темного Клыка');
INSERT INTO `locales_area` VALUES ('210', '', '', '', '', '', '', '', '***Используй меня повторно 2***');
INSERT INTO `locales_area` VALUES ('211', '', '', '', '', '', '', '', 'Заледеневшее озеро');
INSERT INTO `locales_area` VALUES ('212', '', '', '', '', '', '', '', 'Озеро Хельмово Ложе');
INSERT INTO `locales_area` VALUES ('213', '', '', '', '', '', '', '', 'Серебряный рудник');
INSERT INTO `locales_area` VALUES ('214', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('215', '', '', '', '', '', '', '', 'Мулгор');
INSERT INTO `locales_area` VALUES ('219', '', '', '', '', '', '', '', 'Поместье Алекстона');
INSERT INTO `locales_area` VALUES ('220', '', '', '', '', '', '', '', 'Плато Красного Облака');
INSERT INTO `locales_area` VALUES ('221', '', '', '', '', '', '', '', 'Лагерь Нараче');
INSERT INTO `locales_area` VALUES ('222', '', '', '', '', '', '', '', 'Деревня Кровавого Копыта');
INSERT INTO `locales_area` VALUES ('223', '', '', '', '', '', '', '', 'Озеро Каменного Быка');
INSERT INTO `locales_area` VALUES ('224', '', '', '', '', '', '', '', 'Разграбленный караван');
INSERT INTO `locales_area` VALUES ('225', '', '', '', '', '', '', '', 'Красные скалы');
INSERT INTO `locales_area` VALUES ('226', '', '', '', '', '', '', '', 'Струящаяся Тьма');
INSERT INTO `locales_area` VALUES ('227', '', '', '', '', '', '', '', 'Поле Валгана');
INSERT INTO `locales_area` VALUES ('228', '', '', '', '', '', '', '', 'Гробница');
INSERT INTO `locales_area` VALUES ('229', '', '', '', '', '', '', '', 'Удел Ольсена');
INSERT INTO `locales_area` VALUES ('230', '', '', '', '', '', '', '', 'Стена Седогрива');
INSERT INTO `locales_area` VALUES ('231', '', '', '', '', '', '', '', 'Погибель Берена');
INSERT INTO `locales_area` VALUES ('232', '', '', '', '', '', '', '', 'Рассветные острова');
INSERT INTO `locales_area` VALUES ('233', '', '', '', '', '', '', '', 'Янтарная мельница');
INSERT INTO `locales_area` VALUES ('235', '', '', '', '', '', '', '', 'Крепость Фенриса');
INSERT INTO `locales_area` VALUES ('236', '', '', '', '', '', '', '', 'Крепость Темного Клыка');
INSERT INTO `locales_area` VALUES ('237', '', '', '', '', '', '', '', 'Старая переправа');
INSERT INTO `locales_area` VALUES ('238', '', '', '', '', '', '', '', 'Сад Мальдена');
INSERT INTO `locales_area` VALUES ('239', '', '', '', '', '', '', '', 'Делянка Ивара');
INSERT INTO `locales_area` VALUES ('240', '', '', '', '', '', '', '', 'Мертвое поле');
INSERT INTO `locales_area` VALUES ('241', '', '', '', '', '', '', '', 'Гниющий сад');
INSERT INTO `locales_area` VALUES ('242', '', '', '', '', '', '', '', 'Светлая роща');
INSERT INTO `locales_area` VALUES ('243', '', '', '', '', '', '', '', 'Покинутая усадьба');
INSERT INTO `locales_area` VALUES ('244', '', '', '', '', '', '', '', 'Имение Уиппл');
INSERT INTO `locales_area` VALUES ('245', '', '', '', '', '', '', '', 'Усадьба Йоргена');
INSERT INTO `locales_area` VALUES ('246', '', '', '', '', '', '', '', 'Котлован');
INSERT INTO `locales_area` VALUES ('247', '', '', '', '', '', '', '', 'Карьер Грязнули');
INSERT INTO `locales_area` VALUES ('249', '', '', '', '', '', '', '', 'Скала Молота Ужаса');
INSERT INTO `locales_area` VALUES ('250', '', '', '', '', '', '', '', 'Руины Тауриссана');
INSERT INTO `locales_area` VALUES ('251', '', '', '', '', '', '', '', 'Пламенеющий Стяг');
INSERT INTO `locales_area` VALUES ('252', '', '', '', '', '', '', '', 'Крепость Черной горы');
INSERT INTO `locales_area` VALUES ('253', '', '', '', '', '', '', '', 'Башня Пепла');
INSERT INTO `locales_area` VALUES ('254', '', '', '', '', '', '', '', 'Черная гора');
INSERT INTO `locales_area` VALUES ('255', '', '', '', '', '', '', '', 'Алтарь Бурь');
INSERT INTO `locales_area` VALUES ('256', '', '', '', '', '', '', '', 'Альдрассил');
INSERT INTO `locales_area` VALUES ('257', '', '', '', '', '', '', '', 'Паучье логово');
INSERT INTO `locales_area` VALUES ('258', '', '', '', '', '', '', '', 'Пещера Бесов');
INSERT INTO `locales_area` VALUES ('259', '', '', '', '', '', '', '', 'Озеро Аль\'Амет');
INSERT INTO `locales_area` VALUES ('260', '', '', '', '', '', '', '', 'Деревня Звездного Ветра');
INSERT INTO `locales_area` VALUES ('261', '', '', '', '', '', '', '', 'Лагерь у Кривой Сосны');
INSERT INTO `locales_area` VALUES ('262', '', '', '', '', '', '', '', 'Обитель Бен\'этиль');
INSERT INTO `locales_area` VALUES ('263', '', '', '', '', '', '', '', 'Расселина');
INSERT INTO `locales_area` VALUES ('264', '', '', '', '', '', '', '', 'Поляна Оракула');
INSERT INTO `locales_area` VALUES ('265', '', '', '', '', '', '', '', 'Родниковая река');
INSERT INTO `locales_area` VALUES ('266', '', '', '', '', '', '', '', 'Родниковое озеро');
INSERT INTO `locales_area` VALUES ('267', '', '', '', '', '', '', '', 'Предгорья Хилсбрада');
INSERT INTO `locales_area` VALUES ('268', '', '', '', '', '', '', '', 'Кратер Азшары');
INSERT INTO `locales_area` VALUES ('269', '', '', '', '', '', '', '', 'Дун Альгаз');
INSERT INTO `locales_area` VALUES ('271', '', '', '', '', '', '', '', 'Южнобережье');
INSERT INTO `locales_area` VALUES ('272', '', '', '', '', '', '', '', 'Мельница Таррен');
INSERT INTO `locales_area` VALUES ('275', '', '', '', '', '', '', '', 'Крепость Дарнхольд');
INSERT INTO `locales_area` VALUES ('276', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Подгорная тропа');
INSERT INTO `locales_area` VALUES ('277', '', '', '', '', '', '', '', 'Пещеры предгорий');
INSERT INTO `locales_area` VALUES ('278', '', '', '', '', '', '', '', 'Лордамерские выселки');
INSERT INTO `locales_area` VALUES ('279', '', '', '', '', '', '', '', 'Даларан');
INSERT INTO `locales_area` VALUES ('280', '', '', '', '', '', '', '', 'Странбрад');
INSERT INTO `locales_area` VALUES ('281', '', '', '', '', '', '', '', 'Руины Альтерака');
INSERT INTO `locales_area` VALUES ('282', '', '', '', '', '', '', '', 'Логово Раздробленного Хребта');
INSERT INTO `locales_area` VALUES ('283', '', '', '', '', '', '', '', 'Кровавая низина');
INSERT INTO `locales_area` VALUES ('284', '', '', '', '', '', '', '', 'Высокогорье');
INSERT INTO `locales_area` VALUES ('285', '', '', '', '', '', '', '', 'Южная башня');
INSERT INTO `locales_area` VALUES ('286', '', '', '', '', '', '', '', 'Хилсбрадские поля');
INSERT INTO `locales_area` VALUES ('287', '', '', '', '', '', '', '', 'Хилсбрад');
INSERT INTO `locales_area` VALUES ('288', '', '', '', '', '', '', '', 'Лазуритовый рудник');
INSERT INTO `locales_area` VALUES ('289', '', '', '', '', '', '', '', 'Владение Нетандера');
INSERT INTO `locales_area` VALUES ('290', '', '', '', '', '', '', '', 'Дун Гарок');
INSERT INTO `locales_area` VALUES ('293', '', '', '', '', '', '', '', 'Стена Торадина');
INSERT INTO `locales_area` VALUES ('294', '', '', '', '', '', '', '', 'Восточное побережье');
INSERT INTO `locales_area` VALUES ('295', '', '', '', '', '', '', '', 'Западное побережье');
INSERT INTO `locales_area` VALUES ('296', '', '', '', '', '', '', '', 'Южные моря НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('297', '', '', '', '', '', '', '', 'Остров Жагуаро');
INSERT INTO `locales_area` VALUES ('298', '', '', '', '', '', '', '', 'Бухта Барадин');
INSERT INTO `locales_area` VALUES ('299', '', '', '', '', '', '', '', 'Бухта Менетилов');
INSERT INTO `locales_area` VALUES ('300', '', '', '', '', '', '', '', 'Тростниковый берег');
INSERT INTO `locales_area` VALUES ('301', '', '', '', '', '', '', '', 'Гибельный берег');
INSERT INTO `locales_area` VALUES ('302', '', '', '', '', '', '', '', 'Хрустальное взморье');
INSERT INTO `locales_area` VALUES ('303', '', '', '', '', '', '', '', 'Ракушечный пляж');
INSERT INTO `locales_area` VALUES ('305', '', '', '', '', '', '', '', 'Берег Северного прилива');
INSERT INTO `locales_area` VALUES ('306', '', '', '', '', '', '', '', 'Берег Южного прилива');
INSERT INTO `locales_area` VALUES ('307', '', '', '', '', '', '', '', 'Отвесные скалы');
INSERT INTO `locales_area` VALUES ('308', '', '', '', '', '', '', '', 'Зловещее море');
INSERT INTO `locales_area` VALUES ('309', '', '', '', '', '', '', '', 'Гробница Железноборода');
INSERT INTO `locales_area` VALUES ('310', '', '', '', '', '', '', '', 'Хрустальная шахта');
INSERT INTO `locales_area` VALUES ('311', '', '', '', '', '', '', '', 'Руины Абораза');
INSERT INTO `locales_area` VALUES ('312', '', '', '', '', '', '', '', 'Остров Жанейро');
INSERT INTO `locales_area` VALUES ('313', '', '', '', '', '', '', '', 'Северное поместье');
INSERT INTO `locales_area` VALUES ('314', '', '', '', '', '', '', '', 'Ферма Го\'Шека');
INSERT INTO `locales_area` VALUES ('315', '', '', '', '', '', '', '', 'Усадьба Дабири');
INSERT INTO `locales_area` VALUES ('316', '', '', '', '', '', '', '', 'Крепость Тяжелого Кулака');
INSERT INTO `locales_area` VALUES ('317', '', '', '', '', '', '', '', 'Деревня Сухокожих');
INSERT INTO `locales_area` VALUES ('318', '', '', '', '', '', '', '', 'Теснина Сухоусов');
INSERT INTO `locales_area` VALUES ('320', '', '', '', '', '', '', '', 'Опорный пункт');
INSERT INTO `locales_area` VALUES ('321', '', '', '', '', '', '', '', 'Павший Молот');
INSERT INTO `locales_area` VALUES ('322', '', '', '', '', '', '', '', 'Обломки судов Черноводья');
INSERT INTO `locales_area` VALUES ('323', '', '', '', '', '', '', '', 'Лагерь О\'Брина');
INSERT INTO `locales_area` VALUES ('324', '', '', '', '', '', '', '', 'Крепость Стромгард');
INSERT INTO `locales_area` VALUES ('325', '', '', '', '', '', '', '', 'Башня Аратора');
INSERT INTO `locales_area` VALUES ('326', '', '', '', '', '', '', '', 'Святилище');
INSERT INTO `locales_area` VALUES ('327', '', '', '', '', '', '', '', 'Бухта Фальдира');
INSERT INTO `locales_area` VALUES ('328', '', '', '', '', '', '', '', 'Подводный риф');
INSERT INTO `locales_area` VALUES ('330', '', '', '', '', '', '', '', 'Мост Тандола');
INSERT INTO `locales_area` VALUES ('331', '', '', '', '', '', '', '', 'Ясеневый лес');
INSERT INTO `locales_area` VALUES ('332', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('333', '', '', '', '', '', '', '', 'Восточный круг Обуздания');
INSERT INTO `locales_area` VALUES ('334', '', '', '', '', '', '', '', 'Западный Круг Обуздания');
INSERT INTO `locales_area` VALUES ('335', '', '', '', '', '', '', '', 'Внутренний Круг Обуздания');
INSERT INTO `locales_area` VALUES ('336', '', '', '', '', '', '', '', 'Внешний Круг Обуздания');
INSERT INTO `locales_area` VALUES ('337', '', '', '', '', '', '', '', 'Скелет Апокрифана');
INSERT INTO `locales_area` VALUES ('338', '', '', '', '', '', '', '', 'Крепость Ангор');
INSERT INTO `locales_area` VALUES ('339', '', '', '', '', '', '', '', 'Долина Летлор');
INSERT INTO `locales_area` VALUES ('340', '', '', '', '', '', '', '', 'Каргат');
INSERT INTO `locales_area` VALUES ('341', '', '', '', '', '', '', '', 'Лагерь Кош');
INSERT INTO `locales_area` VALUES ('342', '', '', '', '', '', '', '', 'Лагерь Бофф');
INSERT INTO `locales_area` VALUES ('343', '', '', '', '', '', '', '', 'Лагерь Вург');
INSERT INTO `locales_area` VALUES ('344', '', '', '', '', '', '', '', 'Лагерь Кэгг');
INSERT INTO `locales_area` VALUES ('345', '', '', '', '', '', '', '', 'Удел Эгмонда');
INSERT INTO `locales_area` VALUES ('346', '', '', '', '', '', '', '', 'Карьер Тяжелоступа');
INSERT INTO `locales_area` VALUES ('347', '', '', '', '', '', '', '', 'Грот Гнилобрюхих');
INSERT INTO `locales_area` VALUES ('348', '', '', '', '', '', '', '', 'Заоблачный пик');
INSERT INTO `locales_area` VALUES ('349', '', '', '', '', '', '', '', 'Крепость Громового Молота');
INSERT INTO `locales_area` VALUES ('350', '', '', '', '', '', '', '', 'Сторожка Кель\'Данил');
INSERT INTO `locales_area` VALUES ('351', '', '', '', '', '', '', '', 'Осклизлая скала');
INSERT INTO `locales_area` VALUES ('352', '', '', '', '', '', '', '', 'Зун\'вата');
INSERT INTO `locales_area` VALUES ('353', '', '', '', '', '', '', '', 'Шадра\'Алор');
INSERT INTO `locales_area` VALUES ('354', '', '', '', '', '', '', '', 'Джинта\'Алор');
INSERT INTO `locales_area` VALUES ('355', '', '', '', '', '', '', '', 'Алтарь Зула');
INSERT INTO `locales_area` VALUES ('356', '', '', '', '', '', '', '', 'Серадан');
INSERT INTO `locales_area` VALUES ('357', '', '', '', '', '', '', '', 'Фералас');
INSERT INTO `locales_area` VALUES ('358', '', '', '', '', '', '', '', 'Ежевичная лощина');
INSERT INTO `locales_area` VALUES ('359', '', '', '', '', '', '', '', 'Бейл Модан');
INSERT INTO `locales_area` VALUES ('360', '', '', '', '', '', '', '', 'Рудник Торговой Компании');
INSERT INTO `locales_area` VALUES ('361', '', '', '', '', '', '', '', 'Оскверненный лес');
INSERT INTO `locales_area` VALUES ('362', '', '', '', '', '', '', '', 'Колючий Холм');
INSERT INTO `locales_area` VALUES ('363', '', '', '', '', '', '', '', 'Долина Испытаний');
INSERT INTO `locales_area` VALUES ('364', '', '', '', '', '', '', '', 'Логово');
INSERT INTO `locales_area` VALUES ('365', '', '', '', '', '', '', '', 'Грот Пылающего Клинка');
INSERT INTO `locales_area` VALUES ('366', '', '', '', '', '', '', '', 'Утес Колкар');
INSERT INTO `locales_area` VALUES ('367', '', '', '', '', '', '', '', 'Деревня Сен\'джин');
INSERT INTO `locales_area` VALUES ('368', '', '', '', '', '', '', '', 'Острова Эха');
INSERT INTO `locales_area` VALUES ('369', '', '', '', '', '', '', '', 'Громовой хребет');
INSERT INTO `locales_area` VALUES ('370', '', '', '', '', '', '', '', 'Сухая лощина');
INSERT INTO `locales_area` VALUES ('371', '', '', '', '', '', '', '', 'Пещера Пыльного Ветра');
INSERT INTO `locales_area` VALUES ('372', '', '', '', '', '', '', '', 'Крепость Тирагард');
INSERT INTO `locales_area` VALUES ('373', '', '', '', '', '', '', '', 'Берег Разбитых Кораблей');
INSERT INTO `locales_area` VALUES ('374', '', '', '', '', '', '', '', 'Бухта Острорука');
INSERT INTO `locales_area` VALUES ('375', '', '', '', '', '', '', '', 'Взморье Мертвого Глаза');
INSERT INTO `locales_area` VALUES ('377', '', '', '', '', '', '', '', 'Река Строптивая');
INSERT INTO `locales_area` VALUES ('378', '', '', '', '', '', '', '', 'Лагерь Таурахо');
INSERT INTO `locales_area` VALUES ('379', '', '', '', '', '', '', '', 'Дальняя застава');
INSERT INTO `locales_area` VALUES ('380', '', '', '', '', '', '', '', 'Перекресток');
INSERT INTO `locales_area` VALUES ('381', '', '', '', '', '', '', '', 'Каменный карьер');
INSERT INTO `locales_area` VALUES ('382', '', '', '', '', '', '', '', 'Нефтяное болото');
INSERT INTO `locales_area` VALUES ('383', '', '', '', '', '', '', '', 'Сухие холмы');
INSERT INTO `locales_area` VALUES ('384', '', '', '', '', '', '', '', 'Вершина Багрового Тумана');
INSERT INTO `locales_area` VALUES ('385', '', '', '', '', '', '', '', 'Крепость Северной Стражи');
INSERT INTO `locales_area` VALUES ('386', '', '', '', '', '', '', '', 'Забытые пруды');
INSERT INTO `locales_area` VALUES ('387', '', '', '', '', '', '', '', 'Цветущий оазис');
INSERT INTO `locales_area` VALUES ('388', '', '', '', '', '', '', '', 'Застывший оазис');
INSERT INTO `locales_area` VALUES ('390', '', '', '', '', '', '', '', 'Поля Великанов');
INSERT INTO `locales_area` VALUES ('391', '', '', '', '', '', '', '', 'Торговое побережье');
INSERT INTO `locales_area` VALUES ('392', '', '', '', '', '', '', '', 'Кабестан');
INSERT INTO `locales_area` VALUES ('393', '', '', '', '', '', '', '', 'Побережье Черного Копья');
INSERT INTO `locales_area` VALUES ('394', '', '', '', '', '', '', '', 'Озеро Дарроумир НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('395', '', '', '', '', '', '', '', 'Каэр Дэрроу НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('396', '', '', '', '', '', '', '', 'Колодец Заиндевевшего Копыта');
INSERT INTO `locales_area` VALUES ('397', '', '', '', '', '', '', '', 'Колодец Громового Рога');
INSERT INTO `locales_area` VALUES ('398', '', '', '', '', '', '', '', 'Колодец Буйногривых');
INSERT INTO `locales_area` VALUES ('399', '', '', '', '', '', '', '', 'Гряда на горизонте');
INSERT INTO `locales_area` VALUES ('400', '', '', '', '', '', '', '', 'Тысяча Игл');
INSERT INTO `locales_area` VALUES ('401', '', '', '', '', '', '', '', 'Лестница Прилива');
INSERT INTO `locales_area` VALUES ('403', '', '', '', '', '', '', '', 'Таверна \"Последний привал\"');
INSERT INTO `locales_area` VALUES ('404', '', '', '', '', '', '', '', 'Раскопки Бейл\'дана');
INSERT INTO `locales_area` VALUES ('405', '', '', '', '', '', '', '', 'Пустоши');
INSERT INTO `locales_area` VALUES ('406', '', '', '', '', '', '', '', 'Когтистые горы');
INSERT INTO `locales_area` VALUES ('407', '', '', '', '', '', '', '', 'Оргриммар НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('408', '', '', '', '', '', '', '', 'Остров Гиллиджима');
INSERT INTO `locales_area` VALUES ('409', '', '', '', '', '', '', '', 'Остров доктора Лапидиса');
INSERT INTO `locales_area` VALUES ('410', '', '', '', '', '', '', '', 'Каньон Колючего Ветра');
INSERT INTO `locales_area` VALUES ('411', '', '', '', '', '', '', '', 'Убежище Батрана');
INSERT INTO `locales_area` VALUES ('412', '', '', '', '', '', '', '', 'Руины Ордил\'Арана');
INSERT INTO `locales_area` VALUES ('413', '', '', '', '', '', '', '', 'Застава Мейстры');
INSERT INTO `locales_area` VALUES ('414', '', '', '', '', '', '', '', 'Зорамское взморье');
INSERT INTO `locales_area` VALUES ('415', '', '', '', '', '', '', '', 'Астранаар');
INSERT INTO `locales_area` VALUES ('416', '', '', '', '', '', '', '', 'Святилище Эссины');
INSERT INTO `locales_area` VALUES ('417', '', '', '', '', '', '', '', 'Святилище Огненной Расщелины');
INSERT INTO `locales_area` VALUES ('418', '', '', '', '', '', '', '', 'Руины Звездной Пыли');
INSERT INTO `locales_area` VALUES ('419', '', '', '', '', '', '', '', 'Воющая долина');
INSERT INTO `locales_area` VALUES ('420', '', '', '', '', '', '', '', 'Приют Серебряного Ветра');
INSERT INTO `locales_area` VALUES ('421', '', '', '', '', '', '', '', 'Озеро Мистраль');
INSERT INTO `locales_area` VALUES ('422', '', '', '', '', '', '', '', 'Зеркало Небес');
INSERT INTO `locales_area` VALUES ('424', '', '', '', '', '', '', '', 'Озеро Ирис');
INSERT INTO `locales_area` VALUES ('425', '', '', '', '', '', '', '', 'Лунный колодец');
INSERT INTO `locales_area` VALUES ('426', '', '', '', '', '', '', '', 'Приют в Ночных Лесах');
INSERT INTO `locales_area` VALUES ('427', '', '', '', '', '', '', '', 'Тенистый закоулок');
INSERT INTO `locales_area` VALUES ('428', '', '', '', '', '', '', '', 'Ночная поляна');
INSERT INTO `locales_area` VALUES ('429', '', '', '', '', '', '', '', 'Ксавиан');
INSERT INTO `locales_area` VALUES ('430', '', '', '', '', '', '', '', 'Сатирнаар');
INSERT INTO `locales_area` VALUES ('431', '', '', '', '', '', '', '', 'Застава Расщепленного Дерева');
INSERT INTO `locales_area` VALUES ('432', '', '', '', '', '', '', '', 'Обитель Дор\'Данил');
INSERT INTO `locales_area` VALUES ('433', '', '', '', '', '', '', '', 'Река Фалфаррен');
INSERT INTO `locales_area` VALUES ('434', '', '', '', '', '', '', '', 'Холм Демонического Огня');
INSERT INTO `locales_area` VALUES ('435', '', '', '', '', '', '', '', 'Каньон Гибели Демона');
INSERT INTO `locales_area` VALUES ('436', '', '', '', '', '', '', '', 'Гряда Гибели Демона');
INSERT INTO `locales_area` VALUES ('437', '', '', '', '', '', '', '', 'Лесозаготовки Песни Войны');
INSERT INTO `locales_area` VALUES ('438', '', '', '', '', '', '', '', 'Тенистая Крона');
INSERT INTO `locales_area` VALUES ('439', '', '', '', '', '', '', '', 'Мерцающая равнина');
INSERT INTO `locales_area` VALUES ('440', '', '', '', '', '', '', '', 'Танарис');
INSERT INTO `locales_area` VALUES ('441', '', '', '', '', '', '', '', 'Озеро Фалатим');
INSERT INTO `locales_area` VALUES ('442', '', '', '', '', '', '', '', 'Аубердин');
INSERT INTO `locales_area` VALUES ('443', '', '', '', '', '', '', '', 'Руины Матистры');
INSERT INTO `locales_area` VALUES ('444', '', '', '', '', '', '', '', 'Башня Алталакса');
INSERT INTO `locales_area` VALUES ('445', '', '', '', '', '', '', '', 'Водопад Скалистый');
INSERT INTO `locales_area` VALUES ('446', '', '', '', '', '', '', '', 'Башал\'Аран');
INSERT INTO `locales_area` VALUES ('447', '', '', '', '', '', '', '', 'Амет\'Аран');
INSERT INTO `locales_area` VALUES ('448', '', '', '', '', '', '', '', 'Роща Древних');
INSERT INTO `locales_area` VALUES ('449', '', '', '', '', '', '', '', 'Меч Властителя');
INSERT INTO `locales_area` VALUES ('450', '', '', '', '', '', '', '', 'Раскопки рассеянного геолога');
INSERT INTO `locales_area` VALUES ('452', '', '', '', '', '', '', '', 'Туманный Предел');
INSERT INTO `locales_area` VALUES ('453', '', '', '', '', '', '', '', 'Длинный пролив');
INSERT INTO `locales_area` VALUES ('454', '', '', '', '', '', '', '', 'Петляющая река');
INSERT INTO `locales_area` VALUES ('455', '', '', '', '', '', '', '', 'Берлога в Чернолесье');
INSERT INTO `locales_area` VALUES ('456', '', '', '', '', '', '', '', 'Река Скалистая');
INSERT INTO `locales_area` VALUES ('457', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('458', '', '', '', '', '', '', '', 'Золотой Путь');
INSERT INTO `locales_area` VALUES ('459', '', '', '', '', '', '', '', 'Сторожевой пост Алого ордена');
INSERT INTO `locales_area` VALUES ('460', '', '', '', '', '', '', '', 'Приют у Солнечного Камня');
INSERT INTO `locales_area` VALUES ('461', '', '', '', '', '', '', '', 'Утес Ветрорезов');
INSERT INTO `locales_area` VALUES ('463', '', '', '', '', '', '', '', 'Скалистое озеро');
INSERT INTO `locales_area` VALUES ('464', '', '', '', '', '', '', '', 'Мутное озеро');
INSERT INTO `locales_area` VALUES ('465', '', '', '', '', '', '', '', 'Обугленная долина');
INSERT INTO `locales_area` VALUES ('466', '', '', '', '', '', '', '', 'Долина Кровавой Ярости');
INSERT INTO `locales_area` VALUES ('467', '', '', '', '', '', '', '', 'Пик Каменного Когтя');
INSERT INTO `locales_area` VALUES ('468', '', '', '', '', '', '', '', 'Логово Когтя');
INSERT INTO `locales_area` VALUES ('469', '', '', '', '', '', '', '', 'Долина Высокого леса');
INSERT INTO `locales_area` VALUES ('470', '', '', '', '', '', '', '', 'Громовой Утес НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('471', '', '', '', '', '', '', '', 'Плато Дерзкого Ветра');
INSERT INTO `locales_area` VALUES ('472', '', '', '', '', '', '', '', 'Плато Огненного Камня');
INSERT INTO `locales_area` VALUES ('473', '', '', '', '', '', '', '', 'Скала Мантия');
INSERT INTO `locales_area` VALUES ('474', '', '', '', '', '', '', '', 'Вершина Охотников НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('475', '', '', '', '', '', '', '', 'Уступ Духов НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('476', '', '', '', '', '', '', '', 'Вершина Старейшин НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('477', '', '', '', '', '', '', '', 'Руины Жубуваля');
INSERT INTO `locales_area` VALUES ('478', '', '', '', '', '', '', '', 'Пруды Арлитриэна');
INSERT INTO `locales_area` VALUES ('479', '', '', '', '', '', '', '', 'Карьер Ржавой Кувалды');
INSERT INTO `locales_area` VALUES ('480', '', '', '', '', '', '', '', 'Лагерь Э\'Ток');
INSERT INTO `locales_area` VALUES ('481', '', '', '', '', '', '', '', 'Утес Треснувшего Копыта');
INSERT INTO `locales_area` VALUES ('482', '', '', '', '', '', '', '', 'Скальное гнездовье');
INSERT INTO `locales_area` VALUES ('483', '', '', '', '', '', '', '', 'Каньон Визга');
INSERT INTO `locales_area` VALUES ('484', '', '', '', '', '', '', '', 'Застава Вольного Ветра');
INSERT INTO `locales_area` VALUES ('485', '', '', '', '', '', '', '', 'Великий Подъемник');
INSERT INTO `locales_area` VALUES ('486', '', '', '', '', '', '', '', 'Форт Галак');
INSERT INTO `locales_area` VALUES ('487', '', '', '', '', '', '', '', 'Логово Легкоперых');
INSERT INTO `locales_area` VALUES ('488', '', '', '', '', '', '', '', 'Угол Семи Ветров');
INSERT INTO `locales_area` VALUES ('489', '', '', '', '', '', '', '', 'Таланаар');
INSERT INTO `locales_area` VALUES ('490', '', '', '', '', '', '', '', 'Кратер Ун\'Горо');
INSERT INTO `locales_area` VALUES ('491', '', '', '', '', '', '', '', 'Лабиринты Иглошкурых');
INSERT INTO `locales_area` VALUES ('492', '', '', '', '', '', '', '', 'Кладбище Вороньего Холма');
INSERT INTO `locales_area` VALUES ('493', '', '', '', '', '', '', '', 'Лунная поляна');
INSERT INTO `locales_area` VALUES ('495', '', '', '', '', '', '', '', 'Удалите МЕНЯ');
INSERT INTO `locales_area` VALUES ('496', '', '', '', '', '', '', '', 'Деревня Гиблотопь');
INSERT INTO `locales_area` VALUES ('497', '', '', '', '', '', '', '', 'Сторожка \"Болотный огонек\"');
INSERT INTO `locales_area` VALUES ('498', '', '', '', '', '', '', '', 'Логово Кровавой Топи');
INSERT INTO `locales_area` VALUES ('499', '', '', '', '', '', '', '', 'Мглистая пещера');
INSERT INTO `locales_area` VALUES ('500', '', '', '', '', '', '', '', 'Вершина Моггл');
INSERT INTO `locales_area` VALUES ('501', '', '', '', '', '', '', '', 'Место крушения Бизиля');
INSERT INTO `locales_area` VALUES ('502', '', '', '', '', '', '', '', 'Ведьмин холм');
INSERT INTO `locales_area` VALUES ('503', '', '', '', '', '', '', '', 'Сторожевой пост');
INSERT INTO `locales_area` VALUES ('504', '', '', '', '', '', '', '', 'Северная башня');
INSERT INTO `locales_area` VALUES ('505', '', '', '', '', '', '', '', 'Западная башня');
INSERT INTO `locales_area` VALUES ('506', '', '', '', '', '', '', '', 'Разрушенная башня');
INSERT INTO `locales_area` VALUES ('507', '', '', '', '', '', '', '', 'Синяя топь');
INSERT INTO `locales_area` VALUES ('508', '', '', '', '', '', '', '', 'Руины Деревни Каменного Молота');
INSERT INTO `locales_area` VALUES ('509', '', '', '', '', '', '', '', 'Огненное логово');
INSERT INTO `locales_area` VALUES ('510', '', '', '', '', '', '', '', 'Земля Драконов');
INSERT INTO `locales_area` VALUES ('511', '', '', '', '', '', '', '', 'Драконьи топи');
INSERT INTO `locales_area` VALUES ('512', '', '', '', '', '', '', '', 'Логово Ониксии НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('513', '', '', '', '', '', '', '', 'Остров Терамор');
INSERT INTO `locales_area` VALUES ('514', '', '', '', '', '', '', '', 'Цитадель');
INSERT INTO `locales_area` VALUES ('515', '', '', '', '', '', '', '', 'Потайная бухта');
INSERT INTO `locales_area` VALUES ('516', '', '', '', '', '', '', '', 'Пылевая бухта');
INSERT INTO `locales_area` VALUES ('517', '', '', '', '', '', '', '', 'Залив Яростных Волн');
INSERT INTO `locales_area` VALUES ('518', '', '', '', '', '', '', '', 'Зловещий берег');
INSERT INTO `locales_area` VALUES ('536', '', '', '', '', '', '', '', 'Участок Эддла');
INSERT INTO `locales_area` VALUES ('537', '', '', '', '', '', '', '', 'Вулкан Огненного Венца');
INSERT INTO `locales_area` VALUES ('538', '', '', '', '', '', '', '', 'Смоляные ямы Лаккари');
INSERT INTO `locales_area` VALUES ('539', '', '', '', '', '', '', '', 'Путь Ужаса');
INSERT INTO `locales_area` VALUES ('540', '', '', '', '', '', '', '', 'Скользкий овраг');
INSERT INTO `locales_area` VALUES ('541', '', '', '', '', '', '', '', 'Укрытие Маршалла');
INSERT INTO `locales_area` VALUES ('542', '', '', '', '', '', '', '', 'Пещера Лишайников');
INSERT INTO `locales_area` VALUES ('543', '', '', '', '', '', '', '', 'Горячие источники Голакка');
INSERT INTO `locales_area` VALUES ('556', '', '', '', '', '', '', '', 'Озеро Лок');
INSERT INTO `locales_area` VALUES ('576', '', '', '', '', '', '', '', 'Приют Бродяги');
INSERT INTO `locales_area` VALUES ('596', '', '', '', '', '', '', '', 'Кладбище кодо');
INSERT INTO `locales_area` VALUES ('597', '', '', '', '', '', '', '', 'Застава Скитающихся Духов');
INSERT INTO `locales_area` VALUES ('598', '', '', '', '', '', '', '', 'Побережье Сар\'Терис');
INSERT INTO `locales_area` VALUES ('599', '', '', '', '', '', '', '', 'Крепость Громового Топора');
INSERT INTO `locales_area` VALUES ('600', '', '', '', '', '', '', '', 'Пещера Болгана');
INSERT INTO `locales_area` VALUES ('602', '', '', '', '', '', '', '', 'Поле Маннорок');
INSERT INTO `locales_area` VALUES ('603', '', '', '', '', '', '', '', 'Саргерон');
INSERT INTO `locales_area` VALUES ('604', '', '', '', '', '', '', '', 'Деревня Маграм');
INSERT INTO `locales_area` VALUES ('606', '', '', '', '', '', '', '', 'Деревня Гелкис');
INSERT INTO `locales_area` VALUES ('607', '', '', '', '', '', '', '', 'Долина Копий');
INSERT INTO `locales_area` VALUES ('608', '', '', '', '', '', '', '', 'Высота Найджела');
INSERT INTO `locales_area` VALUES ('609', '', '', '', '', '', '', '', 'Деревня Колкар');
INSERT INTO `locales_area` VALUES ('616', '', '', '', '', '', '', '', 'Хиджал');
INSERT INTO `locales_area` VALUES ('618', '', '', '', '', '', '', '', 'Зимние Ключи');
INSERT INTO `locales_area` VALUES ('636', '', '', '', '', '', '', '', 'Волчья река');
INSERT INTO `locales_area` VALUES ('637', '', '', '', '', '', '', '', 'Дольмен Кодо');
INSERT INTO `locales_area` VALUES ('638', '', '', '', '', '', '', '', 'Потайная тропа');
INSERT INTO `locales_area` VALUES ('639', '', '', '', '', '', '', '', 'Священный Камень');
INSERT INTO `locales_area` VALUES ('640', '', '', '', '', '', '', '', 'Святилище Дремлющего Пламени');
INSERT INTO `locales_area` VALUES ('656', '', '', '', '', '', '', '', 'Озеро Элуне\'ара');
INSERT INTO `locales_area` VALUES ('657', '', '', '', '', '', '', '', 'Убежище');
INSERT INTO `locales_area` VALUES ('676', '', '', '', '', '', '', '', 'Запределье');
INSERT INTO `locales_area` VALUES ('696', '', '', '', '', '', '', '', 'Терраса ремесленников НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('697', '', '', '', '', '', '', '', 'Терраса торговцев НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('698', '', '', '', '', '', '', '', 'Храмовые сады НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('699', '', '', '', '', '', '', '', 'Храм Элуны НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('700', '', '', '', '', '', '', '', 'Анклав Кенария НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('701', '', '', '', '', '', '', '', 'Терраса Воинов НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('702', '', '', '', '', '', '', '', 'Деревня Рут\'теран');
INSERT INTO `locales_area` VALUES ('716', '', '', '', '', '', '', '', 'Мастерская Сталекрута');
INSERT INTO `locales_area` VALUES ('717', '', '', '', '', '', '', '', 'Тюрьма');
INSERT INTO `locales_area` VALUES ('718', '', '', '', '', '', '', '', 'Пещеры Стенаний');
INSERT INTO `locales_area` VALUES ('719', '', '', '', '', '', '', '', 'Непроглядная Пучина');
INSERT INTO `locales_area` VALUES ('720', '', '', '', '', '', '', '', 'Остров Битв');
INSERT INTO `locales_area` VALUES ('721', '', '', '', '', '', '', '', 'Гномреган');
INSERT INTO `locales_area` VALUES ('722', '', '', '', '', '', '', '', 'Курганы Иглошкурых');
INSERT INTO `locales_area` VALUES ('736', '', '', '', '', '', '', '', 'Лощина Бен\'этиль');
INSERT INTO `locales_area` VALUES ('796', '', '', '', '', '', '', '', 'Монастырь Алого ордена');
INSERT INTO `locales_area` VALUES ('797', '', '', '', '', '', '', '', 'Лагерь Джерода');
INSERT INTO `locales_area` VALUES ('798', '', '', '', '', '', '', '', 'Дозорная башня');
INSERT INTO `locales_area` VALUES ('799', '', '', '', '', '', '', '', 'Темный берег');
INSERT INTO `locales_area` VALUES ('800', '', '', '', '', '', '', '', 'Туннель Холодной долины');
INSERT INTO `locales_area` VALUES ('801', '', '', '', '', '', '', '', 'Долина Промозглого Ветра');
INSERT INTO `locales_area` VALUES ('802', '', '', '', '', '', '', '', 'Мерцающий хребет');
INSERT INTO `locales_area` VALUES ('803', '', '', '', '', '', '', '', 'Ферма Янтарленов');
INSERT INTO `locales_area` VALUES ('804', '', '', '', '', '', '', '', 'Холмы Тандрид');
INSERT INTO `locales_area` VALUES ('805', '', '', '', '', '', '', '', 'Южные врата');
INSERT INTO `locales_area` VALUES ('806', '', '', '', '', '', '', '', 'Застава у Южных врат');
INSERT INTO `locales_area` VALUES ('807', '', '', '', '', '', '', '', 'Северные врата');
INSERT INTO `locales_area` VALUES ('808', '', '', '', '', '', '', '', 'Застава у Северных врат');
INSERT INTO `locales_area` VALUES ('809', '', '', '', '', '', '', '', 'Врата Стальгорна');
INSERT INTO `locales_area` VALUES ('810', '', '', '', '', '', '', '', 'Тихий Омут');
INSERT INTO `locales_area` VALUES ('811', '', '', '', '', '', '', '', 'Долина Кошмаров');
INSERT INTO `locales_area` VALUES ('812', '', '', '', '', '', '', '', 'Долина ядовитых пауков');
INSERT INTO `locales_area` VALUES ('813', '', '', '', '', '', '', '', 'Бастион');
INSERT INTO `locales_area` VALUES ('814', '', '', '', '', '', '', '', 'Река Строптивая');
INSERT INTO `locales_area` VALUES ('815', '', '', '', '', '', '', '', 'Река Строптивая');
INSERT INTO `locales_area` VALUES ('816', '', '', '', '', '', '', '', 'Земли Иглогривых');
INSERT INTO `locales_area` VALUES ('817', '', '', '', '', '', '', '', 'Скала Черепа');
INSERT INTO `locales_area` VALUES ('818', '', '', '', '', '', '', '', 'Утес Бледногривов');
INSERT INTO `locales_area` VALUES ('819', '', '', '', '', '', '', '', 'Гряда Неистовства Ветра');
INSERT INTO `locales_area` VALUES ('820', '', '', '', '', '', '', '', 'Золотые равнины');
INSERT INTO `locales_area` VALUES ('821', '', '', '', '', '', '', '', 'Холмистые равнины');
INSERT INTO `locales_area` VALUES ('836', '', '', '', '', '', '', '', 'Дун Альгаз');
INSERT INTO `locales_area` VALUES ('837', '', '', '', '', '', '', '', 'Дун Альгаз');
INSERT INTO `locales_area` VALUES ('838', '', '', '', '', '', '', '', 'Северные врата');
INSERT INTO `locales_area` VALUES ('839', '', '', '', '', '', '', '', 'Южные врата');
INSERT INTO `locales_area` VALUES ('856', '', '', '', '', '', '', '', 'Мглистая роща');
INSERT INTO `locales_area` VALUES ('876', '', '', '', '', '', '', '', 'Остров ГМ');
INSERT INTO `locales_area` VALUES ('877', '', '', '', '', '', '', '', 'Удалите МЕНЯ');
INSERT INTO `locales_area` VALUES ('878', '', '', '', '', '', '', '', 'Река Строптивая');
INSERT INTO `locales_area` VALUES ('879', '', '', '', '', '', '', '', 'Река Строптивая');
INSERT INTO `locales_area` VALUES ('880', '', '', '', '', '', '', '', 'Мост Тандола');
INSERT INTO `locales_area` VALUES ('881', '', '', '', '', '', '', '', 'Мост Тандола');
INSERT INTO `locales_area` VALUES ('896', '', '', '', '', '', '', '', 'Остров Очищения');
INSERT INTO `locales_area` VALUES ('916', '', '', '', '', '', '', '', 'Владение Янсена');
INSERT INTO `locales_area` VALUES ('917', '', '', '', '', '', '', '', 'Мертвая пашня');
INSERT INTO `locales_area` VALUES ('918', '', '', '', '', '', '', '', 'Ферма Мольсена');
INSERT INTO `locales_area` VALUES ('919', '', '', '', '', '', '', '', 'Пруд Стенделя');
INSERT INTO `locales_area` VALUES ('920', '', '', '', '', '', '', '', 'Холмы Разбойничьих Кинжалов');
INSERT INTO `locales_area` VALUES ('921', '', '', '', '', '', '', '', 'Участок Демонта');
INSERT INTO `locales_area` VALUES ('922', '', '', '', '', '', '', '', 'Пыльные равнины');
INSERT INTO `locales_area` VALUES ('923', '', '', '', '', '', '', '', 'Долина Камнедробов');
INSERT INTO `locales_area` VALUES ('924', '', '', '', '', '', '', '', 'Долина Королей');
INSERT INTO `locales_area` VALUES ('925', '', '', '', '', '', '', '', 'Станция Альгаз');
INSERT INTO `locales_area` VALUES ('926', '', '', '', '', '', '', '', 'Ферма Баклбри');
INSERT INTO `locales_area` VALUES ('927', '', '', '', '', '', '', '', 'Сияющий берег');
INSERT INTO `locales_area` VALUES ('928', '', '', '', '', '', '', '', 'Северная приливная низина');
INSERT INTO `locales_area` VALUES ('936', '', '', '', '', '', '', '', 'Хребет Седых Лап');
INSERT INTO `locales_area` VALUES ('956', '', '', '', '', '', '', '', 'Зеленеющие поля');
INSERT INTO `locales_area` VALUES ('976', '', '', '', '', '', '', '', 'Прибамбасск');
INSERT INTO `locales_area` VALUES ('977', '', '', '', '', '', '', '', 'Порт Картеля');
INSERT INTO `locales_area` VALUES ('978', '', '', '', '', '', '', '', 'Зул\'Фаррак');
INSERT INTO `locales_area` VALUES ('979', '', '', '', '', '', '', '', 'Застава Скорбных Песков');
INSERT INTO `locales_area` VALUES ('980', '', '', '', '', '', '', '', 'Долина Кактусов');
INSERT INTO `locales_area` VALUES ('981', '', '', '', '', '', '', '', 'Зияющая бездна');
INSERT INTO `locales_area` VALUES ('982', '', '', '', '', '', '', '', 'Ядовитый улей');
INSERT INTO `locales_area` VALUES ('983', '', '', '', '', '', '', '', 'Поселение Песчаного Молота');
INSERT INTO `locales_area` VALUES ('984', '', '', '', '', '', '', '', 'Руины Восточной Луны');
INSERT INTO `locales_area` VALUES ('985', '', '', '', '', '', '', '', 'Родниковое поле');
INSERT INTO `locales_area` VALUES ('986', '', '', '', '', '', '', '', 'Логово Залашьи');
INSERT INTO `locales_area` VALUES ('987', '', '', '', '', '', '', '', 'Пляж на Краю Света');
INSERT INTO `locales_area` VALUES ('988', '', '', '', '', '', '', '', 'Берег Морского Бродяги');
INSERT INTO `locales_area` VALUES ('989', '', '', '', '', '', '', '', 'Ульдум');
INSERT INTO `locales_area` VALUES ('990', '', '', '', '', '', '', '', 'Долина Стражей');
INSERT INTO `locales_area` VALUES ('991', '', '', '', '', '', '', '', 'Застава Ганстена');
INSERT INTO `locales_area` VALUES ('992', '', '', '', '', '', '', '', 'Руины Южной Луны');
INSERT INTO `locales_area` VALUES ('996', '', '', '', '', '', '', '', 'Лагерь Ренда');
INSERT INTO `locales_area` VALUES ('997', '', '', '', '', '', '', '', 'Долина Ренда');
INSERT INTO `locales_area` VALUES ('998', '', '', '', '', '', '', '', 'Скала Ренда');
INSERT INTO `locales_area` VALUES ('999', '', '', '', '', '', '', '', 'Башня Каменной Стражи');
INSERT INTO `locales_area` VALUES ('1000', '', '', '', '', '', '', '', 'Долина Галарделл');
INSERT INTO `locales_area` VALUES ('1001', '', '', '', '', '', '', '', 'Озерный тракт');
INSERT INTO `locales_area` VALUES ('1002', '', '', '', '', '', '', '', 'Три Угла');
INSERT INTO `locales_area` VALUES ('1016', '', '', '', '', '', '', '', 'Зловещий холм');
INSERT INTO `locales_area` VALUES ('1017', '', '', '', '', '', '', '', 'Гряда Ящеров');
INSERT INTO `locales_area` VALUES ('1018', '', '', '', '', '', '', '', 'Черная трясина');
INSERT INTO `locales_area` VALUES ('1019', '', '', '', '', '', '', '', 'Зеленый Пояс');
INSERT INTO `locales_area` VALUES ('1020', '', '', '', '', '', '', '', 'Болото Мохошкуров');
INSERT INTO `locales_area` VALUES ('1021', '', '', '', '', '', '', '', 'Пещера Тельгена');
INSERT INTO `locales_area` VALUES ('1022', '', '', '', '', '', '', '', 'Болота Синежабрых');
INSERT INTO `locales_area` VALUES ('1023', '', '', '', '', '', '', '', 'Долина Солевого Тумана');
INSERT INTO `locales_area` VALUES ('1024', '', '', '', '', '', '', '', 'Закатное болото');
INSERT INTO `locales_area` VALUES ('1025', '', '', '', '', '', '', '', 'Зеленый Пояс');
INSERT INTO `locales_area` VALUES ('1036', '', '', '', '', '', '', '', 'Лагерь Злого Клыка');
INSERT INTO `locales_area` VALUES ('1037', '', '', '', '', '', '', '', 'Грим Батол');
INSERT INTO `locales_area` VALUES ('1038', '', '', '', '', '', '', '', 'Врата Драконьей Пасти');
INSERT INTO `locales_area` VALUES ('1039', '', '', '', '', '', '', '', 'Погибший Флот');
INSERT INTO `locales_area` VALUES ('1056', '', '', '', '', '', '', '', 'Холм Дарроу');
INSERT INTO `locales_area` VALUES ('1057', '', '', '', '', '', '', '', 'Стена Торадина');
INSERT INTO `locales_area` VALUES ('1076', '', '', '', '', '', '', '', 'Паучий тракт');
INSERT INTO `locales_area` VALUES ('1097', '', '', '', '', '', '', '', 'Затихший берег');
INSERT INTO `locales_area` VALUES ('1098', '', '', '', '', '', '', '', 'Поместье Мистмантла');
INSERT INTO `locales_area` VALUES ('1099', '', '', '', '', '', '', '', 'Лагерь Мохаче');
INSERT INTO `locales_area` VALUES ('1100', '', '', '', '', '', '', '', 'Лагерь Зловещего Тотема');
INSERT INTO `locales_area` VALUES ('1101', '', '', '', '', '', '', '', 'Гудящая Бездна');
INSERT INTO `locales_area` VALUES ('1102', '', '', '', '', '', '', '', 'Штормовое озеро');
INSERT INTO `locales_area` VALUES ('1103', '', '', '', '', '', '', '', 'Поселение Гордунни');
INSERT INTO `locales_area` VALUES ('1104', '', '', '', '', '', '', '', 'Мок\'Гордун');
INSERT INTO `locales_area` VALUES ('1105', '', '', '', '', '', '', '', 'Долина Свирепого Утеса');
INSERT INTO `locales_area` VALUES ('1106', '', '', '', '', '', '', '', 'Высокогорье Блеклых Перьев');
INSERT INTO `locales_area` VALUES ('1107', '', '', '', '', '', '', '', 'Озеро Тихого Ветра');
INSERT INTO `locales_area` VALUES ('1108', '', '', '', '', '', '', '', 'Забытый берег');
INSERT INTO `locales_area` VALUES ('1109', '', '', '', '', '', '', '', 'Восточная колонна');
INSERT INTO `locales_area` VALUES ('1110', '', '', '', '', '', '', '', 'Западная колонна');
INSERT INTO `locales_area` VALUES ('1111', '', '', '', '', '', '', '', 'Сонные Ветви');
INSERT INTO `locales_area` VALUES ('1112', '', '', '', '', '', '', '', 'Нефритовое озеро');
INSERT INTO `locales_area` VALUES ('1113', '', '', '', '', '', '', '', 'Онейрос');
INSERT INTO `locales_area` VALUES ('1114', '', '', '', '', '', '', '', 'Руины Яростного Ветра');
INSERT INTO `locales_area` VALUES ('1115', '', '', '', '', '', '', '', 'Пещера Бешеного оврага');
INSERT INTO `locales_area` VALUES ('1116', '', '', '', '', '', '', '', 'Крепость Оперенной Луны');
INSERT INTO `locales_area` VALUES ('1117', '', '', '', '', '', '', '', 'Руины Соларсаля');
INSERT INTO `locales_area` VALUES ('1118', '', '', '', '', '', '', '', 'Низинные чащобы НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1119', '', '', '', '', '', '', '', 'Два Колосса');
INSERT INTO `locales_area` VALUES ('1120', '', '', '', '', '', '', '', 'Остров Сардор');
INSERT INTO `locales_area` VALUES ('1121', '', '', '', '', '', '', '', 'Остров Ужаса');
INSERT INTO `locales_area` VALUES ('1136', '', '', '', '', '', '', '', 'Высокогорные дебри');
INSERT INTO `locales_area` VALUES ('1137', '', '', '', '', '', '', '', 'Низинные чащобы');
INSERT INTO `locales_area` VALUES ('1156', '', '', '', '', '', '', '', 'Южные степи');
INSERT INTO `locales_area` VALUES ('1157', '', '', '', '', '', '', '', 'Южный Золотой Путь');
INSERT INTO `locales_area` VALUES ('1176', '', '', '', '', '', '', '', 'Зул\'Фаррак');
INSERT INTO `locales_area` VALUES ('1196', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Остров Альказ');
INSERT INTO `locales_area` VALUES ('1216', '', '', '', '', '', '', '', 'Крепость Древобрюхов');
INSERT INTO `locales_area` VALUES ('1217', '', '', '', '', '', '', '', 'Лагерь Ванндир');
INSERT INTO `locales_area` VALUES ('1218', '', '', '', '', '', '', '', 'ТЕСТАзшара');
INSERT INTO `locales_area` VALUES ('1219', '', '', '', '', '', '', '', 'Лагерь Легаш');
INSERT INTO `locales_area` VALUES ('1220', '', '', '', '', '', '', '', 'Талассийское поселение');
INSERT INTO `locales_area` VALUES ('1221', '', '', '', '', '', '', '', 'Руины Эльдарата');
INSERT INTO `locales_area` VALUES ('1222', '', '', '', '', '', '', '', 'Гнездо Хетайры');
INSERT INTO `locales_area` VALUES ('1223', '', '', '', '', '', '', '', 'Храм Зин-Малор');
INSERT INTO `locales_area` VALUES ('1224', '', '', '', '', '', '', '', 'Медвежий угол');
INSERT INTO `locales_area` VALUES ('1225', '', '', '', '', '', '', '', 'Урсолан');
INSERT INTO `locales_area` VALUES ('1226', '', '', '', '', '', '', '', 'Храм Арккоран');
INSERT INTO `locales_area` VALUES ('1227', '', '', '', '', '', '', '', 'Залив Бурь');
INSERT INTO `locales_area` VALUES ('1228', '', '', '', '', '', '', '', 'Разоренное побережье');
INSERT INTO `locales_area` VALUES ('1229', '', '', '', '', '', '', '', 'Башня Эльдары');
INSERT INTO `locales_area` VALUES ('1230', '', '', '', '', '', '', '', 'Острые рифы');
INSERT INTO `locales_area` VALUES ('1231', '', '', '', '', '', '', '', 'Южный пляж');
INSERT INTO `locales_area` VALUES ('1232', '', '', '', '', '', '', '', 'Памятник Гребню Ворона');
INSERT INTO `locales_area` VALUES ('1233', '', '', '', '', '', '', '', 'Одинокая вершина');
INSERT INTO `locales_area` VALUES ('1234', '', '', '', '', '', '', '', 'Озеро Меннар');
INSERT INTO `locales_area` VALUES ('1235', '', '', '', '', '', '', '', 'Святилище Песни Теней');
INSERT INTO `locales_area` VALUES ('1236', '', '', '', '', '', '', '', 'Лагерь Халдарр');
INSERT INTO `locales_area` VALUES ('1237', '', '', '', '', '', '', '', 'Храбростан');
INSERT INTO `locales_area` VALUES ('1256', '', '', '', '', '', '', '', 'Опустошенный берег');
INSERT INTO `locales_area` VALUES ('1276', '', '', '', '', '', '', '', 'Туннель Когтя');
INSERT INTO `locales_area` VALUES ('1277', '', '', '', '', '', '', '', 'Туннель Когтя');
INSERT INTO `locales_area` VALUES ('1296', '', '', '', '', '', '', '', 'Ферма Каменного Клыка');
INSERT INTO `locales_area` VALUES ('1297', '', '', '', '', '', '', '', 'Свиноферма');
INSERT INTO `locales_area` VALUES ('1316', '', '', '', '', '', '', '', 'Курганы Иглошкурых');
INSERT INTO `locales_area` VALUES ('1336', '', '', '', '', '', '', '', 'Бухта Сорванных Парусов');
INSERT INTO `locales_area` VALUES ('1337', '', '', '', '', '', '', '', 'Ульдаман');
INSERT INTO `locales_area` VALUES ('1338', '', '', '', '', '', '', '', 'Озеро Лордамер');
INSERT INTO `locales_area` VALUES ('1339', '', '', '', '', '', '', '', 'Озеро Лордамер');
INSERT INTO `locales_area` VALUES ('1357', '', '', '', '', '', '', '', 'Перекресток Висельников');
INSERT INTO `locales_area` VALUES ('1377', '', '', '', '', '', '', '', 'Силитус');
INSERT INTO `locales_area` VALUES ('1397', '', '', '', '', '', '', '', 'Изумрудный лес');
INSERT INTO `locales_area` VALUES ('1417', '', '', '', '', '', '', '', 'Затонувший храм');
INSERT INTO `locales_area` VALUES ('1437', '', '', '', '', '', '', '', 'Форт Молота Ужаса');
INSERT INTO `locales_area` VALUES ('1438', '', '', '', '', '', '', '', 'Крепость Стражей Пустоты');
INSERT INTO `locales_area` VALUES ('1439', '', '', '', '', '', '', '', 'Стоянка Молота Ужаса');
INSERT INTO `locales_area` VALUES ('1440', '', '', '', '', '', '', '', 'Змеиные Кольца');
INSERT INTO `locales_area` VALUES ('1441', '', '', '', '', '', '', '', 'Алтарь Бурь');
INSERT INTO `locales_area` VALUES ('1442', '', '', '', '', '', '', '', 'Гряда Огненной стражи');
INSERT INTO `locales_area` VALUES ('1443', '', '', '', '', '', '', '', 'Шлаковая Яма');
INSERT INTO `locales_area` VALUES ('1444', '', '', '', '', '', '', '', 'Пепельное Море');
INSERT INTO `locales_area` VALUES ('1445', '', '', '', '', '', '', '', 'Черная гора');
INSERT INTO `locales_area` VALUES ('1446', '', '', '', '', '', '', '', 'Лагерь Братства Тория');
INSERT INTO `locales_area` VALUES ('1457', '', '', '', '', '', '', '', 'Мастерские Гарнизона');
INSERT INTO `locales_area` VALUES ('1477', '', '', '', '', '', '', '', 'Храм Атал\'Хаккара');
INSERT INTO `locales_area` VALUES ('1497', '', '', '', '', '', '', '', 'Подгород');
INSERT INTO `locales_area` VALUES ('1517', '', '', '', '', '', '', '', 'Ульдаман');
INSERT INTO `locales_area` VALUES ('1518', '', '', '', '', '', '', '', 'Не использующиеся Мертвые копи');
INSERT INTO `locales_area` VALUES ('1519', '', '', '', '', '', '', '', 'Штормград');
INSERT INTO `locales_area` VALUES ('1537', '', '', '', '', '', '', '', 'Стальгорн');
INSERT INTO `locales_area` VALUES ('1557', '', '', '', '', '', '', '', 'Оплот Треснувшего Копыта');
INSERT INTO `locales_area` VALUES ('1577', '', '', '', '', '', '', '', 'Мыс Тернистой долины');
INSERT INTO `locales_area` VALUES ('1578', '', '', '', '', '', '', '', 'Южный Гибельный берег');
INSERT INTO `locales_area` VALUES ('1579', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Мертвые копи 002');
INSERT INTO `locales_area` VALUES ('1580', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Потайная бухта 003');
INSERT INTO `locales_area` VALUES ('1581', '', '', '', '', '', '', '', 'Мертвые копи');
INSERT INTO `locales_area` VALUES ('1582', '', '', '', '', '', '', '', 'Потайная бухта');
INSERT INTO `locales_area` VALUES ('1583', '', '', '', '', '', '', '', 'Пик Черной горы');
INSERT INTO `locales_area` VALUES ('1584', '', '', '', '', '', '', '', 'Глубины Черной горы');
INSERT INTO `locales_area` VALUES ('1597', '', '', '', '', '', '', '', 'Земли ящеров НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1598', '', '', '', '', '', '', '', 'Ферма Гроль\'дома НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1599', '', '', '', '', '', '', '', 'Лагерь Мор\'шан');
INSERT INTO `locales_area` VALUES ('1600', '', '', '', '', '', '', '', 'Застава Чести НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1601', '', '', '', '', '', '', '', 'Хребет Черный шип НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1602', '', '', '', '', '', '', '', 'Ежевичный Шип НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1603', '', '', '', '', '', '', '', 'Агамагор НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('1617', '', '', '', '', '', '', '', 'Аллея Героев');
INSERT INTO `locales_area` VALUES ('1637', '', '', '', '', '', '', '', 'Оргриммар');
INSERT INTO `locales_area` VALUES ('1638', '', '', '', '', '', '', '', 'Громовой Утес');
INSERT INTO `locales_area` VALUES ('1639', '', '', '', '', '', '', '', 'Вершина Старейшин');
INSERT INTO `locales_area` VALUES ('1640', '', '', '', '', '', '', '', 'Вершина Духов');
INSERT INTO `locales_area` VALUES ('1641', '', '', '', '', '', '', '', 'Вершина Охотников');
INSERT INTO `locales_area` VALUES ('1657', '', '', '', '', '', '', '', 'Дарнас');
INSERT INTO `locales_area` VALUES ('1658', '', '', '', '', '', '', '', 'Анклав Кенария');
INSERT INTO `locales_area` VALUES ('1659', '', '', '', '', '', '', '', 'Терраса Ремесленников');
INSERT INTO `locales_area` VALUES ('1660', '', '', '', '', '', '', '', 'Терраса Воинов');
INSERT INTO `locales_area` VALUES ('1661', '', '', '', '', '', '', '', 'Храмовые сады');
INSERT INTO `locales_area` VALUES ('1662', '', '', '', '', '', '', '', 'Терраса Торговцев');
INSERT INTO `locales_area` VALUES ('1677', '', '', '', '', '', '', '', 'Возвышенность Гэвина');
INSERT INTO `locales_area` VALUES ('1678', '', '', '', '', '', '', '', 'Возвышенность Соферы');
INSERT INTO `locales_area` VALUES ('1679', '', '', '', '', '', '', '', 'Уступ Коррана');
INSERT INTO `locales_area` VALUES ('1680', '', '', '', '', '', '', '', 'Высокий отрог');
INSERT INTO `locales_area` VALUES ('1681', '', '', '', '', '', '', '', 'Мглистый берег');
INSERT INTO `locales_area` VALUES ('1682', '', '', '', '', '', '', '', 'Овчарня Дандреда');
INSERT INTO `locales_area` VALUES ('1683', '', '', '', '', '', '', '', 'Промерзшая пещера');
INSERT INTO `locales_area` VALUES ('1684', '', '', '', '', '', '', '', 'Берег Промозглого Ветра');
INSERT INTO `locales_area` VALUES ('1697', '', '', '', '', '', '', '', 'Земли Ящеров');
INSERT INTO `locales_area` VALUES ('1698', '', '', '', '', '', '', '', 'Ежевичный овраг');
INSERT INTO `locales_area` VALUES ('1699', '', '', '', '', '', '', '', 'Тернистый холм');
INSERT INTO `locales_area` VALUES ('1700', '', '', '', '', '', '', '', 'Агама\'гор');
INSERT INTO `locales_area` VALUES ('1701', '', '', '', '', '', '', '', 'Хребет Черных Шипов');
INSERT INTO `locales_area` VALUES ('1702', '', '', '', '', '', '', '', 'Застава Чести');
INSERT INTO `locales_area` VALUES ('1703', '', '', '', '', '', '', '', 'Застава Мор\'шан');
INSERT INTO `locales_area` VALUES ('1704', '', '', '', '', '', '', '', 'Ферма Гроль\'дома');
INSERT INTO `locales_area` VALUES ('1717', '', '', '', '', '', '', '', 'Лабиринты Иглошкурых');
INSERT INTO `locales_area` VALUES ('1718', '', '', '', '', '', '', '', 'Великий Подъемник');
INSERT INTO `locales_area` VALUES ('1737', '', '', '', '', '', '', '', 'Мглистая долина');
INSERT INTO `locales_area` VALUES ('1738', '', '', '', '', '', '', '', 'Родник Нек\'Мани');
INSERT INTO `locales_area` VALUES ('1739', '', '', '', '', '', '', '', 'Лагерь Кровавого Паруса');
INSERT INTO `locales_area` VALUES ('1740', '', '', '', '', '', '', '', 'Главный лагерь Торговой Компании');
INSERT INTO `locales_area` VALUES ('1741', '', '', '', '', '', '', '', 'Арена Гурубаши');
INSERT INTO `locales_area` VALUES ('1742', '', '', '', '', '', '', '', 'Пещера Духов');
INSERT INTO `locales_area` VALUES ('1757', '', '', '', '', '', '', '', 'Кровавая Завеса');
INSERT INTO `locales_area` VALUES ('1758', '', '', '', '', '', '', '', 'Бурун');
INSERT INTO `locales_area` VALUES ('1759', '', '', '', '', '', '', '', 'Госпожа Удача');
INSERT INTO `locales_area` VALUES ('1760', '', '', '', '', '', '', '', 'Штаб-квартира Торговой Компании');
INSERT INTO `locales_area` VALUES ('1761', '', '', '', '', '', '', '', 'Деревня Мертвого Леса');
INSERT INTO `locales_area` VALUES ('1762', '', '', '', '', '', '', '', 'Деревня Сквернолапов');
INSERT INTO `locales_area` VALUES ('1763', '', '', '', '', '', '', '', 'Джеденар');
INSERT INTO `locales_area` VALUES ('1764', '', '', '', '', '', '', '', 'Река Отравленной Крови');
INSERT INTO `locales_area` VALUES ('1765', '', '', '', '', '', '', '', 'Водопад Отравленной Крови');
INSERT INTO `locales_area` VALUES ('1766', '', '', '', '', '', '', '', 'Долина Рваных Ран');
INSERT INTO `locales_area` VALUES ('1767', '', '', '', '', '', '', '', 'Железнолесье');
INSERT INTO `locales_area` VALUES ('1768', '', '', '', '', '', '', '', 'Пещера Железнолесья');
INSERT INTO `locales_area` VALUES ('1769', '', '', '', '', '', '', '', 'Крепость Древобрюхов');
INSERT INTO `locales_area` VALUES ('1770', '', '', '', '', '', '', '', 'Оплот Теней');
INSERT INTO `locales_area` VALUES ('1771', '', '', '', '', '', '', '', 'Святилище Искусителя');
INSERT INTO `locales_area` VALUES ('1777', '', '', '', '', '', '', '', 'Пещера Итара');
INSERT INTO `locales_area` VALUES ('1778', '', '', '', '', '', '', '', 'Горемрак');
INSERT INTO `locales_area` VALUES ('1779', '', '', '', '', '', '', '', 'Деревня Дренил\'дур');
INSERT INTO `locales_area` VALUES ('1780', '', '', '', '', '', '', '', 'Развилка Расщепленного Копья');
INSERT INTO `locales_area` VALUES ('1797', '', '', '', '', '', '', '', 'Вязкая топь');
INSERT INTO `locales_area` VALUES ('1798', '', '', '', '', '', '', '', 'Ползучая трясина');
INSERT INTO `locales_area` VALUES ('1817', '', '', '', '', '', '', '', 'Пещера у Вязкой топи');
INSERT INTO `locales_area` VALUES ('1837', '', '', '', '', '', '', '', 'Пещеры Сухокожих');
INSERT INTO `locales_area` VALUES ('1857', '', '', '', '', '', '', '', 'Стена Торадина');
INSERT INTO `locales_area` VALUES ('1858', '', '', '', '', '', '', '', 'Камен\'гор');
INSERT INTO `locales_area` VALUES ('1877', '', '', '', '', '', '', '', 'Долина Клыков');
INSERT INTO `locales_area` VALUES ('1878', '', '', '', '', '', '', '', 'Знойные Пески');
INSERT INTO `locales_area` VALUES ('1879', '', '', '', '', '', '', '', 'Маревые равнины');
INSERT INTO `locales_area` VALUES ('1880', '', '', '', '', '', '', '', 'Домик Пероборода');
INSERT INTO `locales_area` VALUES ('1881', '', '', '', '', '', '', '', 'Лагерь Выпивохи');
INSERT INTO `locales_area` VALUES ('1882', '', '', '', '', '', '', '', 'Чумная лощина');
INSERT INTO `locales_area` VALUES ('1883', '', '', '', '', '', '', '', 'Озеро Доблести');
INSERT INTO `locales_area` VALUES ('1884', '', '', '', '', '', '', '', 'Агол\'вата');
INSERT INTO `locales_area` VALUES ('1885', '', '', '', '', '', '', '', 'Хири\'вата');
INSERT INTO `locales_area` VALUES ('1886', '', '', '', '', '', '', '', 'Ползучие руины');
INSERT INTO `locales_area` VALUES ('1887', '', '', '', '', '', '', '', 'Грот Богена');
INSERT INTO `locales_area` VALUES ('1897', '', '', '', '', '', '', '', 'Терраса Творца');
INSERT INTO `locales_area` VALUES ('1898', '', '', '', '', '', '', '', 'Лощина Суховея');
INSERT INTO `locales_area` VALUES ('1917', '', '', '', '', '', '', '', 'Шаол\'вата');
INSERT INTO `locales_area` VALUES ('1937', '', '', '', '', '', '', '', 'Руины Полуденной Тени');
INSERT INTO `locales_area` VALUES ('1938', '', '', '', '', '', '', '', 'Разбитая Колонна');
INSERT INTO `locales_area` VALUES ('1939', '', '', '', '', '', '', '', 'Безбрежные пески');
INSERT INTO `locales_area` VALUES ('1940', '', '', '', '', '', '', '', 'Берег за Южной грядой');
INSERT INTO `locales_area` VALUES ('1941', '', '', '', '', '', '', '', 'Пещеры Времени');
INSERT INTO `locales_area` VALUES ('1942', '', '', '', '', '', '', '', 'Топи');
INSERT INTO `locales_area` VALUES ('1943', '', '', '', '', '', '', '', 'Плато Железного Камня');
INSERT INTO `locales_area` VALUES ('1957', '', '', '', '', '', '', '', 'Обугленная пещера');
INSERT INTO `locales_area` VALUES ('1958', '', '', '', '', '', '', '', 'Палатка Дубильщицы');
INSERT INTO `locales_area` VALUES ('1959', '', '', '', '', '', '', '', 'Выжженная долина');
INSERT INTO `locales_area` VALUES ('1977', '', '', '', '', '', '', '', 'Зул\'Гуруб');
INSERT INTO `locales_area` VALUES ('1978', '', '', '', '', '', '', '', 'Тростниковая застава');
INSERT INTO `locales_area` VALUES ('1997', '', '', '', '', '', '', '', 'Застава Отравленной Крови');
INSERT INTO `locales_area` VALUES ('1998', '', '', '', '', '', '', '', 'Поляна Когтистых Ветвей');
INSERT INTO `locales_area` VALUES ('2017', '', '', '', '', '', '', '', 'Стратхольм');
INSERT INTO `locales_area` VALUES ('2037', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Крепость Темного Клыка 003');
INSERT INTO `locales_area` VALUES ('2057', '', '', '', '', '', '', '', 'Некроситет');
INSERT INTO `locales_area` VALUES ('2077', '', '', '', '', '', '', '', 'Сумеречная долина');
INSERT INTO `locales_area` VALUES ('2078', '', '', '', '', '', '', '', 'Сумеречная излучина');
INSERT INTO `locales_area` VALUES ('2079', '', '', '', '', '', '', '', 'Остров Алькац');
INSERT INTO `locales_area` VALUES ('2097', '', '', '', '', '', '', '', 'Пик Темного Облака');
INSERT INTO `locales_area` VALUES ('2098', '', '', '', '', '', '', '', 'Катакомбы Утреннего Леса');
INSERT INTO `locales_area` VALUES ('2099', '', '', '', '', '', '', '', 'Крепость Каменной Стражи');
INSERT INTO `locales_area` VALUES ('2100', '', '', '', '', '', '', '', 'Мародон');
INSERT INTO `locales_area` VALUES ('2101', '', '', '', '', '', '', '', 'Таверна \"Крепкое пойло\"');
INSERT INTO `locales_area` VALUES ('2102', '', '', '', '', '', '', '', 'Таверна \"Громоварка\"');
INSERT INTO `locales_area` VALUES ('2103', '', '', '', '', '', '', '', 'Крепость Менетил');
INSERT INTO `locales_area` VALUES ('2104', '', '', '', '', '', '', '', 'Таверна \"Большая вода\"');
INSERT INTO `locales_area` VALUES ('2117', '', '', '', '', '', '', '', 'Мрачный склеп');
INSERT INTO `locales_area` VALUES ('2118', '', '', '', '', '', '', '', 'Ратуша Брилла');
INSERT INTO `locales_area` VALUES ('2119', '', '', '', '', '', '', '', 'Таверна \"Петля висельника\"');
INSERT INTO `locales_area` VALUES ('2137', '', '', '', '', '', '', '', 'Пруды ВиденийНЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('2138', '', '', '', '', '', '', '', 'Пещера Багрового Тумана');
INSERT INTO `locales_area` VALUES ('2157', '', '', '', '', '', '', '', 'Крепость Бейл\'дан');
INSERT INTO `locales_area` VALUES ('2158', '', '', '', '', '', '', '', 'Логово Огнебора');
INSERT INTO `locales_area` VALUES ('2159', '', '', '', '', '', '', '', 'Логово Ониксии');
INSERT INTO `locales_area` VALUES ('2160', '', '', '', '', '', '', '', 'Рудник Ветрорезов');
INSERT INTO `locales_area` VALUES ('2161', '', '', '', '', '', '', '', 'Погибель Роланда');
INSERT INTO `locales_area` VALUES ('2177', '', '', '', '', '', '', '', 'Ринг');
INSERT INTO `locales_area` VALUES ('2197', '', '', '', '', '', '', '', 'Пруды Видений');
INSERT INTO `locales_area` VALUES ('2198', '', '', '', '', '', '', '', 'Лощина Тьмы');
INSERT INTO `locales_area` VALUES ('2217', '', '', '', '', '', '', '', 'Деревня Сломанного Копья');
INSERT INTO `locales_area` VALUES ('2237', '', '', '', '', '', '', '', 'Застава Белого Плеса');
INSERT INTO `locales_area` VALUES ('2238', '', '', '', '', '', '', '', 'Горния');
INSERT INTO `locales_area` VALUES ('2239', '', '', '', '', '', '', '', 'Око Зейна');
INSERT INTO `locales_area` VALUES ('2240', '', '', '', '', '', '', '', 'Виражи на Миражах');
INSERT INTO `locales_area` VALUES ('2241', '', '', '', '', '', '', '', 'Уступ Ледопардов');
INSERT INTO `locales_area` VALUES ('2242', '', '', '', '', '', '', '', 'Сокрытая роща');
INSERT INTO `locales_area` VALUES ('2243', '', '', '', '', '', '', '', 'Застава Древобрюхов');
INSERT INTO `locales_area` VALUES ('2244', '', '', '', '', '', '', '', 'Деревня Зимней Спячки');
INSERT INTO `locales_area` VALUES ('2245', '', '', '', '', '', '', '', 'Мазторил');
INSERT INTO `locales_area` VALUES ('2246', '', '', '', '', '', '', '', 'Источники Ледяного огня');
INSERT INTO `locales_area` VALUES ('2247', '', '', '', '', '', '', '', 'Холмы Ледополоха');
INSERT INTO `locales_area` VALUES ('2248', '', '', '', '', '', '', '', 'Дун Мандарр');
INSERT INTO `locales_area` VALUES ('2249', '', '', '', '', '', '', '', 'Теснина Ледяного Шепота');
INSERT INTO `locales_area` VALUES ('2250', '', '', '', '', '', '', '', 'Совиная чаща');
INSERT INTO `locales_area` VALUES ('2251', '', '', '', '', '', '', '', 'Озеро Кел\'Терил');
INSERT INTO `locales_area` VALUES ('2252', '', '', '', '', '', '', '', 'Руины Кел\'Терила');
INSERT INTO `locales_area` VALUES ('2253', '', '', '', '', '', '', '', 'Деревня Звездопада');
INSERT INTO `locales_area` VALUES ('2254', '', '', '', '', '', '', '', 'Берлога Бен\'Таллоу');
INSERT INTO `locales_area` VALUES ('2255', '', '', '', '', '', '', '', 'Круговзор');
INSERT INTO `locales_area` VALUES ('2256', '', '', '', '', '', '', '', 'Теснина Зловещего Шепота');
INSERT INTO `locales_area` VALUES ('2257', '', '', '', '', '', '', '', 'Подземный поезд');
INSERT INTO `locales_area` VALUES ('2258', '', '', '', '', '', '', '', 'Грибная долина');
INSERT INTO `locales_area` VALUES ('2259', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯПоместье Маррисов');
INSERT INTO `locales_area` VALUES ('2260', '', '', '', '', '', '', '', 'Поместье Маррисов');
INSERT INTO `locales_area` VALUES ('2261', '', '', '', '', '', '', '', 'Крипта');
INSERT INTO `locales_area` VALUES ('2262', '', '', '', '', '', '', '', 'Дарроушир');
INSERT INTO `locales_area` VALUES ('2263', '', '', '', '', '', '', '', 'Башня королевской стражи');
INSERT INTO `locales_area` VALUES ('2264', '', '', '', '', '', '', '', 'Перекресток Корина');
INSERT INTO `locales_area` VALUES ('2265', '', '', '', '', '', '', '', 'Лагерь Алого ордена');
INSERT INTO `locales_area` VALUES ('2266', '', '', '', '', '', '', '', 'Длань Тира');
INSERT INTO `locales_area` VALUES ('2267', '', '', '', '', '', '', '', 'Алая Базилика');
INSERT INTO `locales_area` VALUES ('2268', '', '', '', '', '', '', '', 'Часовня Последней Надежды');
INSERT INTO `locales_area` VALUES ('2269', '', '', '', '', '', '', '', 'Лесопилка Бровача');
INSERT INTO `locales_area` VALUES ('2270', '', '', '', '', '', '', '', 'Ядовитая поляна');
INSERT INTO `locales_area` VALUES ('2271', '', '', '', '', '', '', '', 'Восточная башня');
INSERT INTO `locales_area` VALUES ('2272', '', '', '', '', '', '', '', 'Северный Дол');
INSERT INTO `locales_area` VALUES ('2273', '', '', '', '', '', '', '', 'Зул\'Машар');
INSERT INTO `locales_area` VALUES ('2274', '', '', '', '', '', '', '', 'Мазра\'Алор');
INSERT INTO `locales_area` VALUES ('2275', '', '', '', '', '', '', '', 'Башня Северного перевала');
INSERT INTO `locales_area` VALUES ('2276', '', '', '', '', '', '', '', 'Сторожка Кель\'Литиен');
INSERT INTO `locales_area` VALUES ('2277', '', '', '', '', '', '', '', 'Проклятый лес');
INSERT INTO `locales_area` VALUES ('2278', '', '', '', '', '', '', '', 'Оплот Плети');
INSERT INTO `locales_area` VALUES ('2279', '', '', '', '', '', '', '', 'Стратхольм');
INSERT INTO `locales_area` VALUES ('2280', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Стратхольм');
INSERT INTO `locales_area` VALUES ('2297', '', '', '', '', '', '', '', 'Озеро Дарроумир');
INSERT INTO `locales_area` VALUES ('2298', '', '', '', '', '', '', '', 'Каэр Дарроу');
INSERT INTO `locales_area` VALUES ('2299', '', '', '', '', '', '', '', 'Озеро Дарроумир');
INSERT INTO `locales_area` VALUES ('2300', '', '', '', '', '', '', '', 'Пещеры Времени');
INSERT INTO `locales_area` VALUES ('2301', '', '', '', '', '', '', '', 'Деревня Колючего Меха');
INSERT INTO `locales_area` VALUES ('2302', '', '', '', '', '', '', '', 'Трясина');
INSERT INTO `locales_area` VALUES ('2303', '', '', '', '', '', '', '', 'Безветренный каньон');
INSERT INTO `locales_area` VALUES ('2317', '', '', '', '', '', '', '', 'Южные моря');
INSERT INTO `locales_area` VALUES ('2318', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2319', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2320', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2321', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2322', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2323', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2324', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2325', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2326', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2337', '', '', '', '', '', '', '', 'Казармы Колючего Холма');
INSERT INTO `locales_area` VALUES ('2338', '', '', '', '', '', '', '', 'Южные моря');
INSERT INTO `locales_area` VALUES ('2339', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2357', '', '', '', '', '', '', '', 'Лагерь Кровавого Клыка');
INSERT INTO `locales_area` VALUES ('2358', '', '', '', '', '', '', '', 'Лесная Песнь');
INSERT INTO `locales_area` VALUES ('2359', '', '', '', '', '', '', '', 'Деревня Зеленой Лапы');
INSERT INTO `locales_area` VALUES ('2360', '', '', '', '', '', '', '', 'Аванпост Среброкрылых');
INSERT INTO `locales_area` VALUES ('2361', '', '', '', '', '', '', '', 'Ночная Гавань');
INSERT INTO `locales_area` VALUES ('2362', '', '', '', '', '', '', '', 'Святилище Ремула');
INSERT INTO `locales_area` VALUES ('2363', '', '', '', '', '', '', '', 'Кельи Малфуриона');
INSERT INTO `locales_area` VALUES ('2364', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2365', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2366', '', '', '', '', '', '', '', 'Черные топи');
INSERT INTO `locales_area` VALUES ('2367', '', '', '', '', '', '', '', 'Старые предгорья Хилсбрада');
INSERT INTO `locales_area` VALUES ('2368', '', '', '', '', '', '', '', 'Мельница Таррен');
INSERT INTO `locales_area` VALUES ('2369', '', '', '', '', '', '', '', 'Южнобережье');
INSERT INTO `locales_area` VALUES ('2370', '', '', '', '', '', '', '', 'Крепость Дарнхольд');
INSERT INTO `locales_area` VALUES ('2371', '', '', '', '', '', '', '', 'Дун Гарок');
INSERT INTO `locales_area` VALUES ('2372', '', '', '', '', '', '', '', 'Хилсбрадские поля');
INSERT INTO `locales_area` VALUES ('2373', '', '', '', '', '', '', '', 'Восточное побережье');
INSERT INTO `locales_area` VALUES ('2374', '', '', '', '', '', '', '', 'Владение Нетандера');
INSERT INTO `locales_area` VALUES ('2375', '', '', '', '', '', '', '', 'Холм Дарроу');
INSERT INTO `locales_area` VALUES ('2376', '', '', '', '', '', '', '', 'Южная башня');
INSERT INTO `locales_area` VALUES ('2377', '', '', '', '', '', '', '', 'Стена Торадина');
INSERT INTO `locales_area` VALUES ('2378', '', '', '', '', '', '', '', 'Западное побережье');
INSERT INTO `locales_area` VALUES ('2379', '', '', '', '', '', '', '', 'Лазуритовый рудник');
INSERT INTO `locales_area` VALUES ('2397', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2398', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2399', '', '', '', '', '', '', '', 'Великое море');
INSERT INTO `locales_area` VALUES ('2400', '', '', '', '', '', '', '', 'Зловещее море');
INSERT INTO `locales_area` VALUES ('2401', '', '', '', '', '', '', '', 'Зловещее море');
INSERT INTO `locales_area` VALUES ('2402', '', '', '', '', '', '', '', 'Зловещее море');
INSERT INTO `locales_area` VALUES ('2403', '', '', '', '', '', '', '', 'Зловещее море');
INSERT INTO `locales_area` VALUES ('2404', '', '', '', '', '', '', '', 'Тефрис-Аран');
INSERT INTO `locales_area` VALUES ('2405', '', '', '', '', '', '', '', 'Этель-Ретор');
INSERT INTO `locales_area` VALUES ('2406', '', '', '', '', '', '', '', 'Остров Раназьяр');
INSERT INTO `locales_area` VALUES ('2407', '', '', '', '', '', '', '', 'Хижина Кормека');
INSERT INTO `locales_area` VALUES ('2408', '', '', '', '', '', '', '', 'Деревня Ночных Охотников');
INSERT INTO `locales_area` VALUES ('2417', '', '', '', '', '', '', '', 'Перевал Черной горы');
INSERT INTO `locales_area` VALUES ('2418', '', '', '', '', '', '', '', 'Дозор Моргана');
INSERT INTO `locales_area` VALUES ('2419', '', '', '', '', '', '', '', 'Скользкая скала');
INSERT INTO `locales_area` VALUES ('2420', '', '', '', '', '', '', '', 'Тропа Крылатого Ужаса');
INSERT INTO `locales_area` VALUES ('2421', '', '', '', '', '', '', '', 'Драко\'дар');
INSERT INTO `locales_area` VALUES ('2437', '', '', '', '', '', '', '', 'Огненная пропасть');
INSERT INTO `locales_area` VALUES ('2457', '', '', '', '', '', '', '', 'Леса Ночной Песни');
INSERT INTO `locales_area` VALUES ('2477', '', '', '', '', '', '', '', 'Сокрытое море');
INSERT INTO `locales_area` VALUES ('2478', '', '', '', '', '', '', '', 'Морлос\'Аран');
INSERT INTO `locales_area` VALUES ('2479', '', '', '', '', '', '', '', 'Изумрудное святилище');
INSERT INTO `locales_area` VALUES ('2480', '', '', '', '', '', '', '', 'Долина Нефритового Пламени');
INSERT INTO `locales_area` VALUES ('2481', '', '', '', '', '', '', '', 'Руины Констелласа');
INSERT INTO `locales_area` VALUES ('2497', '', '', '', '', '', '', '', 'Горькие плесы');
INSERT INTO `locales_area` VALUES ('2517', '', '', '', '', '', '', '', 'Утес Осквернителя');
INSERT INTO `locales_area` VALUES ('2518', '', '', '', '', '', '', '', 'Павильон Лорисс');
INSERT INTO `locales_area` VALUES ('2519', '', '', '', '', '', '', '', 'Холмы Древолапов');
INSERT INTO `locales_area` VALUES ('2520', '', '', '', '', '', '', '', 'Логово Древолапов');
INSERT INTO `locales_area` VALUES ('2521', '', '', '', '', '', '', '', 'Река Вердантис');
INSERT INTO `locales_area` VALUES ('2522', '', '', '', '', '', '', '', 'Руины Исильдиэна');
INSERT INTO `locales_area` VALUES ('2537', '', '', '', '', '', '', '', 'Застава Зловещего Тотема');
INSERT INTO `locales_area` VALUES ('2538', '', '', '', '', '', '', '', 'Лагерь Апарахе');
INSERT INTO `locales_area` VALUES ('2539', '', '', '', '', '', '', '', 'Малака\'джин');
INSERT INTO `locales_area` VALUES ('2540', '', '', '', '', '', '', '', 'Ущелье Камнепадов');
INSERT INTO `locales_area` VALUES ('2541', '', '', '', '', '', '', '', 'Сиширский каньон');
INSERT INTO `locales_area` VALUES ('2557', '', '', '', '', '', '', '', 'Забытый Город');
INSERT INTO `locales_area` VALUES ('2558', '', '', '', '', '', '', '', 'Овраг Мертвого Ветра');
INSERT INTO `locales_area` VALUES ('2559', '', '', '', '', '', '', '', 'Река Алмазная');
INSERT INTO `locales_area` VALUES ('2560', '', '', '', '', '', '', '', 'Лагерь Аридена');
INSERT INTO `locales_area` VALUES ('2561', '', '', '', '', '', '', '', 'Погань');
INSERT INTO `locales_area` VALUES ('2562', '', '', '', '', '', '', '', 'Каражан');
INSERT INTO `locales_area` VALUES ('2563', '', '', '', '', '', '', '', 'Надел Моргана');
INSERT INTO `locales_area` VALUES ('2577', '', '', '', '', '', '', '', 'Забытый Город');
INSERT INTO `locales_area` VALUES ('2597', '', '', '', '', '', '', '', 'Альтеракская долина');
INSERT INTO `locales_area` VALUES ('2617', '', '', '', '', '', '', '', 'Лагерь Заржавня');
INSERT INTO `locales_area` VALUES ('2618', '', '', '', '', '', '', '', 'Холм Нефритового Пламени');
INSERT INTO `locales_area` VALUES ('2619', '', '', '', '', '', '', '', 'Река Тондрорил');
INSERT INTO `locales_area` VALUES ('2620', '', '', '', '', '', '', '', 'Река Тондрорил');
INSERT INTO `locales_area` VALUES ('2621', '', '', '', '', '', '', '', 'Озеро Мерельдар');
INSERT INTO `locales_area` VALUES ('2622', '', '', '', '', '', '', '', 'Моровой овраг');
INSERT INTO `locales_area` VALUES ('2623', '', '', '', '', '', '', '', 'Чумной овраг');
INSERT INTO `locales_area` VALUES ('2624', '', '', '', '', '', '', '', 'Озеро Чернолесья');
INSERT INTO `locales_area` VALUES ('2625', '', '', '', '', '', '', '', 'Восточные ворота');
INSERT INTO `locales_area` VALUES ('2626', '', '', '', '', '', '', '', 'Туннель Ужаса');
INSERT INTO `locales_area` VALUES ('2627', '', '', '', '', '', '', '', 'Долина Ужаса');
INSERT INTO `locales_area` VALUES ('2637', '', '', '', '', '', '', '', 'Крепость Каргатия');
INSERT INTO `locales_area` VALUES ('2657', '', '', '', '', '', '', '', 'Долина Костей');
INSERT INTO `locales_area` VALUES ('2677', '', '', '', '', '', '', '', 'Логово Крыла Тьмы');
INSERT INTO `locales_area` VALUES ('2697', '', '', '', '', '', '', '', 'Перекресток Мертвеца');
INSERT INTO `locales_area` VALUES ('2717', '', '', '', '', '', '', '', 'Огненные Недра');
INSERT INTO `locales_area` VALUES ('2737', '', '', '', '', '', '', '', 'Стена Скарабея');
INSERT INTO `locales_area` VALUES ('2738', '', '', '', '', '', '', '', 'Деревня Южного Ветра');
INSERT INTO `locales_area` VALUES ('2739', '', '', '', '', '', '', '', 'Сумеречный лагерь');
INSERT INTO `locales_area` VALUES ('2740', '', '', '', '', '', '', '', 'Долина Кристаллов');
INSERT INTO `locales_area` VALUES ('2741', '', '', '', '', '', '', '', 'Помост Скарабея');
INSERT INTO `locales_area` VALUES ('2742', '', '', '', '', '', '', '', 'Улей Аши');
INSERT INTO `locales_area` VALUES ('2743', '', '', '', '', '', '', '', 'Улей Зора');
INSERT INTO `locales_area` VALUES ('2744', '', '', '', '', '', '', '', 'Улей Регал');
INSERT INTO `locales_area` VALUES ('2757', '', '', '', '', '', '', '', 'Святилище Павшего Воина');
INSERT INTO `locales_area` VALUES ('2777', '', '', '', '', '', '', '', 'НЕ ИСПОЛЬЗУЕТСЯ Альтеракская долина');
INSERT INTO `locales_area` VALUES ('2797', '', '', '', '', '', '', '', 'Непроглядная Пучина');
INSERT INTO `locales_area` VALUES ('2817', '', '', '', '', '', '', '', '***Используй меня повторно 4***');
INSERT INTO `locales_area` VALUES ('2837', '', '', '', '', '', '', '', 'Хозяйский погреб');
INSERT INTO `locales_area` VALUES ('2838', '', '', '', '', '', '', '', 'Подгорная тропа');
INSERT INTO `locales_area` VALUES ('2839', '', '', '', '', '', '', '', 'Альтеракская долина');
INSERT INTO `locales_area` VALUES ('2857', '', '', '', '', '', '', '', 'Гремящая Клеть');
INSERT INTO `locales_area` VALUES ('2877', '', '', '', '', '', '', '', 'Глыба Тест');
INSERT INTO `locales_area` VALUES ('2897', '', '', '', '', '', '', '', 'Форт Зорам\'гар');
INSERT INTO `locales_area` VALUES ('2917', '', '', '', '', '', '', '', 'Зал Легенд');
INSERT INTO `locales_area` VALUES ('2918', '', '', '', '', '', '', '', 'Зал Защитника');
INSERT INTO `locales_area` VALUES ('2937', '', '', '', '', '', '', '', 'Поселок Грош\'гок');
INSERT INTO `locales_area` VALUES ('2938', '', '', '', '', '', '', '', 'Спящая теснина');
INSERT INTO `locales_area` VALUES ('2957', '', '', '', '', '', '', '', 'Железный рудник');
INSERT INTO `locales_area` VALUES ('2958', '', '', '', '', '', '', '', 'Форт Каменного Очага');
INSERT INTO `locales_area` VALUES ('2959', '', '', '', '', '', '', '', 'Дун Болдар');
INSERT INTO `locales_area` VALUES ('2960', '', '', '', '', '', '', '', 'Перевал Ледяного Крыла');
INSERT INTO `locales_area` VALUES ('2961', '', '', '', '', '', '', '', 'Деревня Северного Волка');
INSERT INTO `locales_area` VALUES ('2962', '', '', '', '', '', '', '', 'Смотровая башня');
INSERT INTO `locales_area` VALUES ('2963', '', '', '', '', '', '', '', 'Рудник Ледяного Зуба');
INSERT INTO `locales_area` VALUES ('2964', '', '', '', '', '', '', '', 'Форт Ледяной Секиры');
INSERT INTO `locales_area` VALUES ('2977', '', '', '', '', '', '', '', 'Гарнизон Стылой Крови');
INSERT INTO `locales_area` VALUES ('2978', '', '', '', '', '', '', '', 'Крепость Северного Волка');
INSERT INTO `locales_area` VALUES ('2979', '', '', '', '', '', '', '', 'Ферма Тор\'кренов');
INSERT INTO `locales_area` VALUES ('3017', '', '', '', '', '', '', '', 'Перевал Ледяного Клинка');
INSERT INTO `locales_area` VALUES ('3037', '', '', '', '', '', '', '', 'Лагерь Железного Камня');
INSERT INTO `locales_area` VALUES ('3038', '', '', '', '', '', '', '', 'Кратер Криворука');
INSERT INTO `locales_area` VALUES ('3039', '', '', '', '', '', '', '', 'Руины Тахонды');
INSERT INTO `locales_area` VALUES ('3057', '', '', '', '', '', '', '', 'Поле брани');
INSERT INTO `locales_area` VALUES ('3058', '', '', '', '', '', '', '', 'Пещера Ледяного Крыла');
INSERT INTO `locales_area` VALUES ('3077', '', '', '', '', '', '', '', 'Погост Отважных');
INSERT INTO `locales_area` VALUES ('3097', '', '', '', '', '', '', '', 'Роящаяся вершина');
INSERT INTO `locales_area` VALUES ('3098', '', '', '', '', '', '', '', 'Сумеречная застава');
INSERT INTO `locales_area` VALUES ('3099', '', '', '', '', '', '', '', 'Сумеречный форт');
INSERT INTO `locales_area` VALUES ('3100', '', '', '', '', '', '', '', 'Разоренный Сумеречный лагерь');
INSERT INTO `locales_area` VALUES ('3117', '', '', '', '', '', '', '', 'Убежище Шалзару');
INSERT INTO `locales_area` VALUES ('3137', '', '', '', '', '', '', '', 'Застава Талрендис');
INSERT INTO `locales_area` VALUES ('3138', '', '', '', '', '', '', '', 'Святилище Ретресса');
INSERT INTO `locales_area` VALUES ('3139', '', '', '', '', '', '', '', 'Обитель Лунного Ужаса');
INSERT INTO `locales_area` VALUES ('3140', '', '', '', '', '', '', '', 'Пещера Чешуеборода');
INSERT INTO `locales_area` VALUES ('3157', '', '', '', '', '', '', '', 'Пещера Камнепадов');
INSERT INTO `locales_area` VALUES ('3177', '', '', '', '', '', '', '', 'Рабочий лагерь Песни Войны');
INSERT INTO `locales_area` VALUES ('3197', '', '', '', '', '', '', '', 'Лагерь Промозглого Ветра');
INSERT INTO `locales_area` VALUES ('3217', '', '', '', '', '', '', '', 'Ристалище');
INSERT INTO `locales_area` VALUES ('3237', '', '', '', '', '', '', '', 'Молот НЕ ИСПОЛЬЗУЕТСЯ');
INSERT INTO `locales_area` VALUES ('3257', '', '', '', '', '', '', '', 'Кости Граккаронда');
INSERT INTO `locales_area` VALUES ('3277', '', '', '', '', '', '', '', 'Ущелье Песни Войны');
INSERT INTO `locales_area` VALUES ('3297', '', '', '', '', '', '', '', 'Кладбище Северного Волка');
INSERT INTO `locales_area` VALUES ('3298', '', '', '', '', '', '', '', 'Перевал Северного Волка');
INSERT INTO `locales_area` VALUES ('3299', '', '', '', '', '', '', '', 'Перевал Дун Болдар');
INSERT INTO `locales_area` VALUES ('3300', '', '', '', '', '', '', '', 'Кладбище Стылой Крови');
INSERT INTO `locales_area` VALUES ('3301', '', '', '', '', '', '', '', 'Кладбище Снегопада');
INSERT INTO `locales_area` VALUES ('3302', '', '', '', '', '', '', '', 'Кладбище Каменного Очага');
INSERT INTO `locales_area` VALUES ('3303', '', '', '', '', '', '', '', 'Кладбище Грозовой Вершины');
INSERT INTO `locales_area` VALUES ('3304', '', '', '', '', '', '', '', 'Укрытие Ледяного Крыла');
INSERT INTO `locales_area` VALUES ('3305', '', '', '', '', '', '', '', 'Укрытие Каменного Очага');
INSERT INTO `locales_area` VALUES ('3306', '', '', '', '', '', '', '', 'Гряда Дикой Лапы');
INSERT INTO `locales_area` VALUES ('3317', '', '', '', '', '', '', '', 'Деревня Сломанного Клыка');
INSERT INTO `locales_area` VALUES ('3318', '', '', '', '', '', '', '', 'Обелиск Дуротана');
INSERT INTO `locales_area` VALUES ('3319', '', '', '', '', '', '', '', 'Роща Среброкрылых');
INSERT INTO `locales_area` VALUES ('3320', '', '', '', '', '', '', '', 'Лесопилка Песни Войны');
INSERT INTO `locales_area` VALUES ('3321', '', '', '', '', '', '', '', 'Крепость Среброкрылых');
INSERT INTO `locales_area` VALUES ('3337', '', '', '', '', '', '', '', 'Пещера Дикой Лапы');
INSERT INTO `locales_area` VALUES ('3338', '', '', '', '', '', '', '', 'Сокрытое ущелье');
INSERT INTO `locales_area` VALUES ('3357', '', '', '', '', '', '', '', 'Остров Йоджамба');
INSERT INTO `locales_area` VALUES ('3358', '', '', '', '', '', '', '', 'Низина Арати');
INSERT INTO `locales_area` VALUES ('3377', '', '', '', '', '', '', '', 'Змеиное Кольцо');
INSERT INTO `locales_area` VALUES ('3378', '', '', '', '', '', '', '', 'Алтарь Хир\'ика');
INSERT INTO `locales_area` VALUES ('3379', '', '', '', '', '', '', '', 'Шадра\'заар');
INSERT INTO `locales_area` VALUES ('3380', '', '', '', '', '', '', '', 'Земли Хаккари');
INSERT INTO `locales_area` VALUES ('3381', '', '', '', '', '', '', '', 'Холм Ширвалла');
INSERT INTO `locales_area` VALUES ('3382', '', '', '', '', '', '', '', 'Храм Бетекк');
INSERT INTO `locales_area` VALUES ('3383', '', '', '', '', '', '', '', 'Алтарь Кипящей Крови');
INSERT INTO `locales_area` VALUES ('3384', '', '', '', '', '', '', '', 'Алтарь Бога Крови');
INSERT INTO `locales_area` VALUES ('3397', '', '', '', '', '', '', '', 'Пирамида Занзы');
INSERT INTO `locales_area` VALUES ('3398', '', '', '', '', '', '', '', 'Грань Безумия');
INSERT INTO `locales_area` VALUES ('3417', '', '', '', '', '', '', '', 'Зал Троллебоя');
INSERT INTO `locales_area` VALUES ('3418', '', '', '', '', '', '', '', 'Логово Осквернителя');
INSERT INTO `locales_area` VALUES ('3419', '', '', '', '', '', '', '', 'Стоянка Пэгла');
INSERT INTO `locales_area` VALUES ('3420', '', '', '', '', '', '', '', 'Ферма');
INSERT INTO `locales_area` VALUES ('3421', '', '', '', '', '', '', '', 'Кузница');
INSERT INTO `locales_area` VALUES ('3422', '', '', '', '', '', '', '', 'Лесопилка');
INSERT INTO `locales_area` VALUES ('3423', '', '', '', '', '', '', '', 'Золотой рудник');
INSERT INTO `locales_area` VALUES ('3424', '', '', '', '', '', '', '', 'Стойла');
INSERT INTO `locales_area` VALUES ('3425', '', '', '', '', '', '', '', 'Крепость Кенария');
INSERT INTO `locales_area` VALUES ('3426', '', '', '', '', '', '', '', 'Лагерь Оленьего Шлема');
INSERT INTO `locales_area` VALUES ('3427', '', '', '', '', '', '', '', 'Лагерь Бронзоборода');
INSERT INTO `locales_area` VALUES ('3428', '', '', '', '', '', '', '', 'Ан\'Кираж');
INSERT INTO `locales_area` VALUES ('3429', '', '', '', '', '', '', '', 'Руины Ан\'Киража');
INSERT INTO `locales_area` VALUES ('3446', '', '', '', '', '', '', '', 'Сумеречная пещера');
INSERT INTO `locales_area` VALUES ('3447', '', '', '', '', '', '', '', 'Укрытие Ортелла');
INSERT INTO `locales_area` VALUES ('3448', '', '', '', '', '', '', '', 'Терраса Скарабея');
INSERT INTO `locales_area` VALUES ('3449', '', '', '', '', '', '', '', 'Терраса Генерала');
INSERT INTO `locales_area` VALUES ('3450', '', '', '', '', '', '', '', 'Резервуар');
INSERT INTO `locales_area` VALUES ('3451', '', '', '', '', '', '', '', 'Инкубатор');
INSERT INTO `locales_area` VALUES ('3452', '', '', '', '', '', '', '', 'Соты');
INSERT INTO `locales_area` VALUES ('3453', '', '', '', '', '', '', '', 'Терраса Стражей');
INSERT INTO `locales_area` VALUES ('3454', '', '', '', '', '', '', '', 'Руины Ан\'Киража');
INSERT INTO `locales_area` VALUES ('3456', '', '', '', '', '', '', '', 'Наксрамас');
INSERT INTO `locales_area` VALUES ('3459', '', '', '', '', '', '', '', 'Город');
INSERT INTO `locales_area` VALUES ('3478', '', '', '', '', '', '', '', 'Врата Ан\'Киража');
INSERT INTO `locales_area` VALUES ('3486', '', '', '', '', '', '', '', 'Поместье Черного Ворона');

