INSERT INTO `migrations` VALUES ('20170110163154');

-- missing UD strath scripts
REPLACE INTO `script_texts` (`entry`, `content_default`, `content_loc2`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000020', 'Intruders! More pawns of the Argent Dawn, no doubt. I already count one of their number among my prisoners. Withdraw from my domain before she is executed!', 'Des intrus ! Encore des marionnettes de l\'Aube d\'argent, sans doute. J\'en ai déjà une parmi mes prisonniers. Hâtez-vous de quitter nom domaine, sans quoi elle sera exécutée !', '0', '6', '0', '0', 'rivendare YELL_45MIN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000021', 'You\'re still here? Your foolishness is amusing! The Argent Dawn wench needn\'t suffer in vain. Leave at once and she shall be spared!', '0', '6', '0', '0', 'rivendare YELL_10MIN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `content_loc2`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000022', 'I shall take great pleasure in taking this poor wretch\'s life! It\'s not too late, she needn\'t suffer in vain. Turn back and her death shall be merciful!', 'Je vais prendre beaucoup de plaisir à tuer cette pauvre femme ! Il n\'est pas trop tard, Il n\'est pas nécessaire qu\'elle souffre pour rien. Allez-vous-en et sa mort sera miséricordieuse !', '0', '6', '0', '0', 'rivendare YELL_5MIN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `content_loc2`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000023', 'Don\'t worry about me! Slay this dreadful beast and cleanse this world of his foul taint!', 'Ne vous inquiétez pas de moi ! Tuez cette bête odieuse ! Libérez le monde de sa vile corruption !', '0', '6', '0', '0', 'ysida YELL_5MIN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000024', 'May this prisoner\'s death serve as a warning. None shall defy the Scourge and live!', '0', '6', '0', '0', 'rivendare YELL_FAILED');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000025', 'So you see fit to toy with the Lich King\'s creations? Ramstein, be sure to give the intruders a proper greeting.', '0', '6', '0', '0', 'rivendare YELL_RAMMSTEIN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000026', 'Ramstein hunger for flesh!', '0', '6', '0', '0', 'rammstein YELL_SPAWN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000027', 'Who dares disturb our master?', '0', '6', '0', '0', 'black_guard_sentry YELL_SPAWN');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000028', 'Time to take matters into my own hands. Come. Enter my domain and challenge the might of the Scourge!', '0', '6', '0', '0', 'rivendare YELL_READY');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000029', 'My death means nothing.... light... will... prevail!', '0', '6', '0', '0', 'ysida YELL_FAILED');
REPLACE INTO `script_texts` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1000030', 'You did it... you\'ve slain Baron Rivendare! The Argent Dawn shall hear of your valiant deeds!', '0', '0', '0', '0', 'ysida SAY_REWARD');
