-- Nostalrius commands
-- Acces ranks:
-- 0 PLAYER
-- 1 NEW GAMEMASTER [Only contact with players]
-- 2 GAMEMASTER [Unstuck, some basic information and sanctions]
-- 3 CONFIRMED GAMEMASTER [Completely confirmed GM, can ban]
-- 4 BASIC ADMIN [Has modification commands]
-- 5 DEV ON PTR [Has debug commands]
-- 6 MAIN ADMIN [All rights, except dangerous/security commands]
-- 7 CONSOLE [All rights, except dangerous commands]

DELETE FROM command;
INSERT INTO command (name, security, help) VALUES
("account characters", 2, "Syntax: .account characters [$accountId|$accountName]\r\n\r\nShow list all characters for account selected by provided $accountId or $accountName, or for selected player in game."),
("account create", 7, "Syntax: .account create $account $password\r\n\r\nCreate account and set password to it."),
("account delete", 7, "Syntax: .account delete $account\r\n\r\nDelete account with all characters."),
("account onlinelist", 1, "Syntax: .account onlinelist\r\n\r\nShow list of online accounts."),
("account lock", 0, "Syntax: .account lock [on|off]\r\n\r\nAllow login from account only from current used IP or remove this requirement."),
("account set", 6, ""),
("account set addon", 4, "Syntax: .account set addon [$accountId|$accountName] $addon\r\n\r\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk."),
("account set gmlevel", 7, "Syntax: .account set gmlevel [$accountId|$accountName] $level\r\n\r\nSet the security level for targeted player (can\'t be used at self) or for $accountId or $accountName to a level of $level.\r\n\r\n$level may range from 0 to 3."),
("account set password", 7, "Syntax: .account set password ($accountId|$accountName) $password $password\r\n\r\nSet password for account."),
("account password", 1, "Syntax: .account password $old_password $new_password $new_password\r\n\r\nChange your account password."),
("account", 0, "Syntax: .account\r\n\r\nDisplay the access level of your account."),
("auction alliance", 2, "Syntax: .auction alliance\r\n\r\nShow alliance auction store independent from your team."),
("auction goblin", 2, "Syntax: .auction goblin\r\n\r\nShow goblin auction store common for all teams."),
("auction horde", 2, "Syntax: .auction horde\r\n\r\nShow horde auction store independent from your team."),
("auction", 2, "Syntax: .auction\r\n\r\nShow your team auction store."),
("cast back", 5, "Syntax: .cast back $spellid [triggered]\r\n  Selected target will cast $spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag."),
("cast dist", 5, "Syntax: .cast dist $spellid [$dist [triggered]]\r\n  You will cast spell to pint at distance $dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells."),
("cast self", 5, "Syntax: .cast self $spellid [triggered]\r\nCast $spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag."),
("cast target", 5, "Syntax: .cast target $spellid [triggered]\r\n  Selected target will cast $spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag."),
("cast", 5, "Syntax: .cast $spellid [triggered]\r\n  Cast $spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag."),
("channel join", 2, "Syntax: .channel join $channel_name\r\n\r\nJoins a channel with given name"),
("channel leave", 2, "Syntax: .channel leave $channel_name\r\n\r\nLeaves a channel with given $channel_name"),
("character deleted", 5, ""),
("character deleted delete", 7, "Syntax: .character deleted delete $guid|$name\r\n\r\nCompletely deletes the selected characters.\r\nIf $name is supplied, only characters with that string in their name will be deleted, if $guid is supplied, only the character with that GUID will be deleted."),
("character deleted list", 5, "Syntax: .character deleted list [$guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if $guid is supplied, only the character with that GUID will be selected."),
("character deleted restore", 5, "Syntax: .character deleted restore $guid|$name [$newname] [$new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If $newaccount is set, the character will be restored to specific account character list. This works only with one character!"),
("character deleted old", 7, "Syntax: .character deleted old [$keepDays]\r\n\r\nCompletely deletes all characters with deleted time longer $keepDays. If $keepDays not provided the  used value from mangosd.conf option \'CharDelete.KeepDays\'. If referenced config option disabled (use 0 value) then command can\'t be used without $keepDays."),
("character erase", 7, "Syntax: .character erase $name\r\n\r\nDelete character $name. Character finally deleted in case any deleting options."),
("character level", 5, "Syntax: .character level [$playername] [$level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by $numberoflevels Or +1 if no $numberoflevels provided). If $numberoflevels is omitted, the level will be increase by 1. If $numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost."),
("character rename", 4, "Syntax: .character rename [$name]\r\n\r\nMark selected in game or by $name in command character for rename at next login."),
("character reputation", 2, "Syntax: .character reputation [$player_name]\r\n\r\nShow reputation information for selected player or player find by $player_name."),
("character race", 7, "Syntax: .character race $newRaceNumber\r\nChanges the race of the selected player."),
("character skin", 7, "Syntax: .character skin $playerName\r\nApply $playerName skin to your target. Make sure that both have the same race !"),
("character fillflys", 7, "Syntax: character fillflys\r\nUnlock all flys for the selected player."),
("character flags", 7, "Syntax: character flags\r\nDisplays / changes selected player 'customFlags' field."),
("character recup", 7, "Syntax: character recup $recupId\r\nApplies character recuperation $recupId to selected player. Cf character tables 'recup*'"),
("character clean", 7, ""),
("character clean todelete", 7, "Syntax: character clean todelete\r\nDelete character whose guid is in `characters_guid_delete`"),
("character clean items", 7, "Syntax: character clean items\r\nDelete items whose guid is in `characters_item_delete`"),
("debug", 5, ""),
("debug anim", 5, "Syntax: .debug anim $emoteid\r\n\r\nPlay emote $emoteid for your character."),
("debug bg", 5, "Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player."),
("debug getitemstate", 5, "Syntax: .debug getitemstate $state\r\nDisplays target items in state $state.\r\nPossible values for $state: new, changed, unchanged, removed, queue, all"),
("debug lrecipient", 5, "Displays selected creature loot recipient."),
("debug getitemvalue", 5, "Syntax: .debug getitemvalue $itemguid $field [int|hex|bit|float]\r\n\r\nGet the field $field of the item $itemguid in your inventroy.\r\n\r\nUse type arg for set output format: int (decimal number), hex (hex value), bit (bitstring), float. By default use integer output."),
("debug getvalue", 5, "Syntax: .debug getvalue $field [int|hex|bit|float]\r\n\r\nGet the field $field of the selected target. If no target is selected, get the content of your field.\r\n\r\nUse type arg for set output format: int (decimal number), hex (hex value), bit (bitstring), float. By default use integer output."),
("debug moditemvalue", 5, "Syntax: .debug moditemvalue $guid $field [int|float| &= | |= | &=~ ] $value\r\n\r\nModify the field $field of the item $itemguid in your inventroy by value $value. \r\n\r\nUse type arg for set mode of modification: int (normal add/subtract $value as decimal number), float (add/subtract $value as float number), &= (bit and, set to 0 all bits in value if it not set to 1 in $value as hex number), |= (bit or, set to 1 all bits in value if it set to 1 in $value as hex number), &=~ (bit and not, set to 0 all bits in value if it set to 1 in $value as hex number). By default expect integer add/subtract."),
("debug modvalue", 5, "Syntax: .debug modvalue $field [int|float| &= | |= | &=~ ] $value\r\n\r\nModify the field $field of the selected target by value $value. If no target is selected, set the content of your field.\r\n\r\nUse type arg for set mode of modification: int (normal add/subtract $value as decimal number), float (add/subtract $value as float number), &= (bit and, set to 0 all bits in value if it not set to 1 in $value as hex number), |= (bit or, set to 1 all bits in value if it set to 1 in $value as hex number), &=~ (bit and not, set to 0 all bits in value if it set to 1 in $value as hex number). By default expect integer add/subtract."),
("debug play", 5, ""),
("debug play cinematic", 5, "Syntax: .debug play cinematic $cinematicid\r\n\r\nPlay cinematic $cinematicid for you. You stay at place while your mind fly.\r\n"),
("debug play sound", 5, "Syntax: .debug play sound $soundid\r\n\r\nPlay sound with $soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds..."),
("debug send", 5, ""),
("debug send buyerror", 5, "Player::SendBuyError"),
("debug send channelnotify", 5, "Syntax: .debug send channelnotify $code\r\nSends SMSG_CHANNEL_NOTIFY."),
("debug send chatmmessage", 5, ""),
("debug send equiperror", 5, ""),
("debug send opcode", 5, "Open opcode.txt and send corresponding Packet.\r\nFile format: opcode [valType1 value1 [valType2 value2]]\r\nAllowed types: uint8, uint16, uint32, uint64, float, string, pguid (target packed guid)"),
("debug send poi", 5, ""),
("debug send qpartymsg", 5, ""),
("debug send qinvalidmsg", 5, ""),
("debug send sellerror", 5, ""),
("debug send spellfail", 5, "Test SMSG_CAST_FAILED"),
("debug send visual", 5, "Syntax: .debug send visual $spellId\r\nSends SMSG_PLAY_SPELL_VISUAL and sets channel values for channeled spells."),
("debug send impact", 5, "Syntax: .debug send visual $spellId\r\nSends SMSG_PLAY_SPELL_IMPACT (on selected unit)"),
("debug setaurastate", 5, ""),
("debug setitemvalue", 5, "Syntax: .debug setitemvalue $guid $field [int|hex|bit|float] $value\r\n\r\nSet the field $field of the item $itemguid in your inventroy to value $value.\r\n\r\nUse type arg for set input format: int (decimal number), hex (hex value), bit (bitstring), float. By default expect integer input format."),
("debug setvalue", 5, "Syntax: .debug setvalue $field [int|hex|bit|float] $value\r\n\r\nSet the field $field of the selected target to value $value. If no target is selected, set the content of your field.\r\n\r\nUse type arg for set input format: int (decimal number), hex (hex value), bit (bitstring), float. By default expect integer input format."),
("debug spellcheck", 5, ""),
("debug spellcoefs", 5, "Syntax: .debug spellcoefs $spellid\r\n\r\nShow default calculated and DB stored coefficients for direct/dot heal/damage."),
("debug spellmods", 5, "Syntax: .debug spellmods (flat|pct) $spellMaskBitIndex $spellModOp $value\r\n\r\nSet at client side spellmod affect for spell that have bit set with index $spellMaskBitIndex in spell family mask for values dependent from spellmod $spellModOp to $value."),
("debug uws", 5, ""),
("debug update", 5, ""),
("debug loottable", 5, ".debug loottable $table $lootid [$itemid]\r\nGenerates 1000 loot rolls for $lootid in $table. Only displays $itemid if specified.\r\nPossible values for $table: creature, fishing, gameobject, item, mail, pickpocketing, skinning, disenchant\r\nNOTE: The loot is generated for your target (for faction/quest depend items for example)"),
("debug forceupdate", 5, ""),
("debug los", 5, ""),
("debug los check", 5, "Checks LoS, from you to selected unit, and displays collision Model."),
("debug los allow", 5, "Generates file with los exceptions. Cf vmaps extracting process."),
("debug moveto", 5, "Syntax: .debug moveto [$movePointOptions=0]\r\nMoves to selected unit."),
("debug assert", 5, "ASSERT(false). Check anticrash."),
("debug pvpcredit", 5, ""),
("debug unitstate", 5, "Syntax: .debug unitstate [$newUnitState]\r\nDisplay / change selection unitstate flags."),
("debug control", 5, "Syntax: .debug control on|off\r\nEnable or disable client control for selection"),
("debug monster", 5, "Test MonsterTextEmote/MonsterWhisper and chat packets structure."),
("debug target", 5, "Syntax: .debug target [$debugFlags]\r\nDisplay some debug data related to your target."),
("debug time", 5, "Syntax: .debug time [$multiplicator]\r\nMultiply server time by a factor."),
("debug moveflags", 5, "Syntax: .debug moveflags [$moveFlagsAsHEX]\r\nDisplay or change target moveflags"),
("debug movespline", 5, "Syntax: .debug movespline\r\nDisplay debug about target current movement"),
("debug dump", 4, "Syntax: .debug dump\r\nDump packets send to the server by targeted player to a file."),
("debug movemotion", 5, "Syntax: .debug movemotion $moveType\r\nChange target motion generator to idle (0), random (1), confused (2), or fleeing (3)"),
("debug factionchange_items", 5, "Attempt to find items not handled by faction change tables."),
("event list", 3, "Syntax: .event list\r\nShow list of currently active events.\r\nShow list of all events"),
("event start", 4, "Syntax: .event start $event_id\r\nStart event $event_id. Set start time for event to current moment (change not saved in DB)."),
("event stop", 4, "Syntax: .event stop $event_id\r\nStop event $event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB)."),
("event", 4, "Syntax: .event $event_id\r\nShow details about event with $event_id."),
("gm chat", 1, "Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided."),
("gm fly", 2, "Syntax: .gm fly [on/off]\r\nEnable or disable GM fly mode.\r\nWarning: this is a fake swim mode instead, so move with your mouse and do not jump"),
("gm ingame", 1, "Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters."),
("gm list", 6, "Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels."),
("gm visible", 4, "Syntax: .gm visible [on/off/level]\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players. You can specify an invisibility level (should be lower or equal to your account security)."),
("gm options", 5, "Syntax: .gm option $option. Option can be GOD, CAST, SPEED, POWER, CRIT, CHECK, PROC, VIDEO"),
("gm setview", 2, "Syntax: .gm setview\r\n\r\nSet farsight view on selected unit. Select yourself to set view back."),
("gm", 1, "Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided."),
("honor", 4, ""),
("honor add", 6, "Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained in lifetime) to the selected player."),
("honor addkill", 6, "Syntax: .honor addkikll\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)"),
("honor show", 4, "Syntax: .honor show\r\n\r\nDisplay the honor stats of the selected player"),
("honor update", 8, "Syntax: .honor update\r\n\r\nForce honor to be update"),
("honor flush", 7, "Do weekly PvP maintenance."),
("honor debug", 5, "Syntax: .honor debug [A/H]\r\nDisplay breakpoints used in PvP ranks computation."),
("honor setrp", 3, "Syntax: .honor setrp $rankPoints\r\nChange YOUR current ranking points."),
("go creature", 2, "Syntax: .go creature ($creature_guid|$creature_name|id $creature_id)\r\nTeleport your character to creature with guid $creature_guid, or teleport your character to creature with name including as part $creature_name substring, or teleport your character to a creature that was spawned from the template with this entry $creature_id."),
("go graveyard", 2, "Syntax: .go graveyard $graveyardId\r\n Teleport to graveyard with the graveyardId specified."),
("go grid", 2, "Syntax: .go grid $gridX $gridY [$mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map $mapId (or current map if it not provided)."),
("go object", 2, "Syntax: .go object ($gameobject_guid|$gameobject_name|id $gameobject_id)\r\nTeleport your character to gameobject with guid $gameobject_guid, or teleport your character to gameobject with name including as part $gameobject_name substring, or teleport your character to a gameobject that was spawned from the template with this entry $gameobject_id."),
("go taxinode", 2, "Syntax: .go taxinode $taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart"),
("go trigger", 2, "Syntax: .go trigger ($trigger_id|$trigger_shift-link|$trigger_target_shift-link) [target]\r\n\r\nTeleport your character to areatrigger with id $trigger_id or trigger id associated with shift-link. If additional arg \"target\" provided then character will telported to areatrigger target point."),
("go zonexy", 2, "Syntax: .go zonexy $x $y [$zone]\r\n\r\nTeleport player to point with ($x,$y) client coordinates at ground(water) level in zone $zoneid or current zone if $zoneid not provided. You can look up zone using .lookup area $namepart"),
("go xy", 2, "Syntax: .go xy $x $y [$mapid]\r\n\r\nTeleport player to point with ($x,$y) coordinates at ground(water) level at map $mapid or same map if $mapid not provided."),
("go xyz", 2, "Syntax: .go xyz $x $y $z [$mapid]\r\n\r\nTeleport player to point with ($x,$y,$z) coordinates at ground(water) level at map $mapid or same map if $mapid not provided."),
("go forward", 2, "Syntax: .go forward $relativeDist\r\nGo forward of $relativeDist units."),
("go up", 2, "Syntax: .go up $relativeDist\r\nGo up of $relativeDist units."),
("go relative", 2, "Syntax: .go relative $forward $left $up\r\nTeleport relative to your current orientation"),
("go warsong", 5, "Syntax: .go warsong\r\nJoin Warsong Gulch from anywhere"),
("go arathi", 5, "Syntax: .go arathi\r\nJoin Arathi Basin from anywhere"),
("go alterac", 5, "Syntax: .go alterac\r\nJoin Alterac battleground from anywhere"),
("go", 5, "Syntax: .go  [$playername|pointlink|$x $y $z [$mapid]]\r\nTeleport your character to point with coordinates of player $playername, or coordinates of one from shift-link types: player, tele, taxinode, creature/creature_entry, gameobject/gameobject_entry, or explicit $x $y $z $mapid coordinates."),
("gobject", 5, ""),
("gobject add", 5, "Syntax: .gobject add $id <spawntimeSecs>\r\n\r\nAdd a game object from game object templates to the world at your current location using the $id.\r\nspawntimesecs sets the spawntime, it is optional.\r\n\r\nNote: this is a copy of .gameobject."),
("gobject tmpadd", 4, "Syntax: .gobject tmpadd $goEntry\r\nSpawn a temporary gameobject (not saved in database, removed at logout)"),
("gobject delete", 5, "Syntax: .gobject delete $go_guid\r\nDelete gameobject with guid $go_guid."),
("gobject move", 5, "Syntax: .gobject move $goguid [$x $y $z]\r\n\r\nMove gameobject $goguid to character coordinates (or to ($x,$y,$z) coordinates if its provide)."),
("gobject near", 2, "Syntax: .gobject near  [$distance]\r\n\r\nOutput gameobjects at distance $distance from player. Output gameobject guids and coordinates sorted by distance from character. If $distance not provided use 10 as default value."),
("gobject target", 2, "Syntax: .gobject target [$go_id|$go_name_part]\r\n\r\nLocate and show position nearest gameobject. If $go_id or $go_name_part provide then locate and show position of nearest gameobject with gameobject template id $go_id or name included $go_name_part as part."),
("gobject turn", 3, "Syntax: .gobject turn $goguid \r\n\r\nSet for gameobject $goguid orientation same as current character orientation."),
("gobject select", 3, "Syntax: .gobject select\r\n\r\nSelects nearest gameobject (within 10 yards)."),
("gobject despawn", 3, "Syntax: .gobject despawn\r\n\r\nDespawns selected gobj using 'gobject select'. The gameobject will respawn after normal respawn time, or never if it is dynamically spawned."),
("gobject toggle", 2, "Syntax: .gobject toggle\r\n\r\nOpens a closed door / closed an opened door. Select the door using 'gobject select'"),
("gobject reset", 5, "Syntax: .gobject reset\r\n\r\nResets selected gameobject to original state."),
("gobject respawn", 5, "Syntax: .gobject respawn\r\n\r\nRespawns despawned selected gameobject."),
("guild", 5, ""),
("guild create", 5, "Syntax: .guild create [$GuildLeaderName] \"$GuildName\"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes."),
("guild delete", 4, "Syntax: .guild delete \"$GuildName\"\r\n\r\nDelete guild $GuildName. Guild name must in quotes."),
("guild invite", 4, "Syntax: .guild invite [$CharacterName] \"$GuildName\"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes."),
("guild uninvite", 5, "Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild."),
("guild rank", 5, "Syntax: .guild rank $CharacterName $Rank\r\n\r\nSet for $CharacterName rank $Rank in a guild."),
("instance", 2, ""),
("instance continents", 4, "Syntax: .instance continents\r\n  Lists instanciated areas in continents and give statistics"),
("instance listbinds", 2, "Syntax: .instance listbinds\r\n  Lists the binds of the selected player."),
("instance unbind", 3, "Syntax: .instance unbind all\r\n  All of the selected player\'s binds will be cleared.\r\n.instance unbind $mapid\r\n Only the specified $mapid instance will be cleared."),
("instance perfinfos", 5, "Syntax: .instance perfinfos\r\n  Shows statistics about current instance performances."),
("instance stats", 2, "Syntax: .instance stats\r\n  Shows statistics about instances."),
("instance savedata", 3, "Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB."),
("instance switch", 5, "Syntax: .instance switch $newInstId\r\n  Changes your target instance ID on a continent"),
("learn all", 5, "Syntax: .learn all\r\n\r\nLearn all big set different spell maybe useful for Administaror."),
("learn all_gm", 5, "Syntax: .learn all_gm\r\n\r\nLearn all default spells for Game Masters."),
("learn all_crafts", 5, "Syntax: .learn crafts\r\n\r\nLearn all professions and recipes."),
("learn all_default", 5, "Syntax: .learn all_default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests."),
("learn all_lang", 5, "Syntax: .learn all_lang\r\n\r\nLearn all languages"),
("learn all_myclass", 5, "Syntax: .learn all_myclass\r\n\r\nLearn all spells and talents available for his class."),
("learn all_myspells", 5, "Syntax: .learn all_myspells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class."),
("learn all_mytalents", 5, "Syntax: .learn all_mytalents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class."),
("learn all_recipes", 5, "Syntax: .learn all_recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all_recipes enchanting"),
("learn", 5, "Syntax: .learn $spell [all]\r\n\r\nSelected character learn a spell of id $spell. If \'all\' provided then all ranks learned."),
("list", 5, ""),
("list auras", 2, "List target auras"),
("list creature", 2, "Syntax: .list creature $creature_id [$max_count]\r\n\r\nOutput creatures with creature id $creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum $max_count creatures. If $max_count not provided use 10 as default value."),
("list item", 7, "Syntax: .list item $item_id [$max_count]\r\n\r\nOutput items with item id $item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum $max_count items. If $max_count not provided use 10 as default value."),
("list object", 2, "Syntax: .list object $gameobject_id [$max_count]\r\n\r\nOutput gameobjects with gameobject id $gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum $max_count gameobject. If $max_count not provided use 10 as default value."),
("list talents", 2, "Syntax: .list talents\r\n\r\nShow list all really known (as learned spells) talent rank spells for selected player or self."),
("lookup", 1, ""),
("lookup account", 2, ""),
("lookup account email", 4, "Syntax: .lookup account email $emailpart [$limit] \r\n\r\n Searchs accounts, which email including $emailpart with optional parametr $limit of results. If $limit not provided expected 100."),
("lookup account ip", 6, "Syntax: lookup account ip $ippart [$limit] \r\n\r\n Searchs accounts, which last used ip inluding $ippart (textual) with optional parametr $$limit of results. If $limit not provided expected 100."),
("lookup account name", 3, "Syntax: .lookup account name $accountpart [$limit] \r\n\r\n Searchs accounts, which username including $accountpart with optional parametr $limit of results. If $limit not provided expected 100."),
("lookup area", 2, "Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s."),
("lookup creature", 2, "Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s."),
("lookup event", 2, "Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name."),
("lookup faction", 2, "Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name."),
("lookup item", 2, "Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s."),
("lookup itemset", 2, "Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s."),
("lookup object", 2, "Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s."),
("lookup quest", 2, "Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s."),
("lookup player", 3, "Syntax: .lookup player $namepart\r\n\r\nLooks up a player by $namepart, and returns all matches."),
("lookup player account", 3, "Syntax: .lookup player account $accountpart [$limit] \r\n\r\n Searchs players, which account username including $accountpart with optional parametr $limit of results. If $limit not provided expected 100."),
("lookup player email", 3, "Syntax: .lookup player email $emailpart [$limit] \r\n\r\n Searchs players, which account email including $emailpart with optional parametr $limit of results. If $limit not provided expected 100."),
("lookup player ip", 3, "Syntax: .lookup player ip $ippart [$limit] \r\n\r\n Searchs players, which account last used ip inluding $ippart (textual) with optional parametr $limit of results. If $limit not provided expected 100."),
("lookup pool", 2, "Syntax: .lookup pool $pooldescpart\r\n\r\nList of pools (anywhere) with substring in description."),
("lookup skill", 2, "Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s."),
("lookup spell", 2, "Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s."),
("lookup taxinode", 2, "Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name."),
("lookup tele", 2, "Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name."),
("modify", 2, ""),
("modify hp", 5, "Syntax: .modify hp $newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp."),
("modify mana", 5, "Syntax: .modify mana $newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana."),
("modify rage", 5, "Syntax: .modify rage $newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage."),
("modify energy", 5, "Syntax: .modify energy $energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy."),
("modify money", 6, "Syntax: .modify money $money\r\n.money $money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n $gold can be negative to remove money."),
("modify speed", 2, "Syntax: .modify speed $rate\r\n.speed $rate\r\n\r\nModify the running speed of the selected player to \"normal base run speed\"*rate. If no player is selected, modify your speed.\r\n\r\n $rate may range from 0.1 to 10."),
("modify swim", 2, "Syntax: .modify swim $rate\r\n\r\nModify the swim speed of the selected player to \"normal swim speed\"*rate. If no player is selected, modify your speed.\r\n\r\n $rate may range from 0.1 to 10."),
("modify scale", 5, "Syntax: .modify scale $scale\r\n\r\nChange model scale for targeted player (until relogin) or creature (until respawn)."),
("modify bwalk", 2, "Syntax: .modify bwalk $rate\r\n\r\nModify the speed of the selected player while running backwards to \"normal walk back speed\"*rate. If no player is selected, modify your speed.\r\n\r\n $rate may range from 0.1 to 10."),
("modify aspeed", 2, "Syntax: .modify aspeed $rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to \"normalbase speed for this move type\"*rate. If no player is selected, modify your speed.\r\n\r\n $rate may range from 0.1 to 10."),
("modify faction", 5, "Syntax: .modify faction $factionid $flagid $npcflagid $dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature."),
("modify tp", 5, "Syntax: .modify tp $tp\r\nSet target free talent points to $tp"),
("modify mount", 5, "Syntax: .modify mount $id $speed\r\nDisplay selected player as mounted at $id creature and set speed to $speed value."),
("modify honor", 6, "Syntax: .modify honor $field $value\r\n\r\nAdd $value to an honor $field (it\'s just for debug , values won\'t be saved at player logout)\r\nField list: points / rank / todaykills / yesterdaykills / yesterdayhonor /\r\nthisweekkills / thisweekhonor / lastweekkills / lastweekhonor /\r\nlastweekstanding / lifetimedishonorablekills / lifetimehonorablekills "),
("modify rep", 6, "Syntax: .modify rep $repId ($repvalue | $rankname [$delta])\r\nSets the selected players reputation with faction $repId to $repvalue or to $reprank.\r\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\r\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id."),
("modify drunk", 5, "Syntax: .modify drunk $value\r\n Set drunk level to $value (0..100). Value 0 remove drunk state, 100 is max drunked state."),
("modify standstate", 5, "Syntax: .modify standstate $emoteid\r\n\r\nChange the emote of your character while standing to $emoteid."),
("modify morph", 5, "Syntax: .modify morph $displayid\r\n\r\nChange your current model id to $displayid."),
("modify gender", 5, "Syntax: .modify gender male/female\r\n\r\nChange gender of selected player."),
("npc", 1, ""),
("npc add", 5, "Syntax: .npc add $creatureid\r\n\r\nSpawn a creature by the given template id of $creatureid."),
("npc additem", 5, "Syntax: .npc additem $itemId <$maxcount><$incrtime>r\r\n\r\nAdd item $itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring."),
("npc addmove", 5, "Syntax: .npc addmove $creature_guid [$waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid $creature_guid. And optional add wait time."),
("npc aiinfo", 5, "Syntax: .npc npc aiinfo\r\n\r\nShow npc AI and script information."),
("npc allowmove", 5, "Syntax: .npc allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented."),
("npc changeentry", 5, "Syntax: .npc allowmove $newEntry\r\nChange targeted unit entry to $newEntry (not saved in database)."),
("npc changelevel", 5, "Syntax: .npc changelevel $level\r\n\r\nChange the level of the selected creature to $level.\r\n\r\n$level may range from 1 to 63."),
("npc delete", 5, "Syntax: .npc delete [$guid]\r\n\r\nDelete creature with guid $guid (or the selected if no guid is provided)"),
("npc delitem", 5, "Syntax: .npc delitem $itemId\r\n\r\nRemove item $itemid from item list of selected vendor."),
("npc factionid", 5, "Syntax: .npc factionid $factionid\r\n\r\nSet the faction of the selected creature to $factionid."),
("npc flag", 5, "Syntax: .npc flag $npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to $npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load."),
("npc follow", 5, "Syntax: .npc follow\r\n\r\nSelected creature start follow you until death/fight/etc."),
("npc info", 4, "Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor."),
("npc move", 5, "Syntax: .npc move [$creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates."),
("npc playemote", 5, "Syntax: .npc playemote $emoteid\r\n\r\nMake the selected creature emote with an emote of id $emoteid."),
("npc setmodel", 5, "Syntax: .npc setmodel $displayid\r\n\r\nChange the model id of the selected creature to $displayid."),
("npc setmovetype", 5, "Syntax: .npc setmovetype [$creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by $creature_guid (or selected if $creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints."),
("npc spawndist", 5, "Syntax: .npc spawndist $dist\r\n\r\nAdjust spawndistance of selected creature to dist."),
("npc spawntime", 5, "Syntax: .npc spawntime $time \r\n\r\nAdjust spawntime of selected creature to time."),
("npc say", 4, "Syntax: .npc say $text\r\nMake the selected npc says $text."),
("npc summon", 5, "Syntax: .npc summon $creatureid\r\n\r\nTemporary summons $creatureid. Despawns at death."),
("npc textemote", 4, "Syntax: .npc textemote $emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id $emoteid."),
("npc unfollow", 4, "Syntax: .npc unfollow\r\n\r\nSelected creature (non pet) stop follow you."),
("npc whisper", 4, "Syntax: .npc whisper $playerguid $text\r\nMake the selected npc whisper $text to $playerguid."),
("npc yell", 4, "Syntax: .npc yell $text\r\nMake the selected npc yells $text."),
("npc tame", 5, "Syntax: .npc tame\r\n\r\nTame selected creature (tameable non pet creature). You don\'t must have pet."),
("npc setdeathstate", 5, "Syntax: .npc setdeathstate on/off\r\n\r\nSet default death state (dead/alive) for npc at spawn."),
("npc group", 5, ""),
("npc group add", 5, "Syntax: .npc group add $leaderGuid [$flags]\r\nAdd selected creature to a group. Possible flags:\r\nOPTION_FORMATION_MOVE (0x001)\r\nOPTION_AGGRO_TOGETHER (0x002)\r\nOPTION_EVADE_TOGETHER (0x004)\r\nOPTION_RESPAWN_TOGETHER (0x008)\r\nOPTION_RESPAWN_ALL_ON_MASTER_EVADE (0x010)\r\nOPTION_RESPAWN_ALL_ON_ANY_EVADE (0x020)\r\n"),
("npc group del", 5, "Syntax: .npc group del\r\nRemove targeted creature from group."),
("npc addweapon", 5, "Not yet implemented."),
("npc name", 5, "Syntax: .npc name $name\r\n\r\nChange the name of the selected creature or character to $name.\r\n\r\nCommand disabled."),
("npc subname", 5, "Syntax: .npc subname $Name\r\n\r\nChange the subname of the selected creature or player to $Name.\r\n\r\nCommand disabled."),
("pet list", 3, "Syntax: .pet list $characterName\r\n\r\nLists given character pets (active and stabled)."),
("pet rename", 4, "Syntax: .pet rename $petId $newName\r\n\r\nRenames given pet id. May not work if the player is online."),
("pet delete", 4, "Syntax: .pet delete $petId\r\n\r\nPermanently removes pet id. May not work if the player is online."),
("pbcast stats", 5, "Syntax: .bcast stats\r\n\r\nDisplays statistics about running packet broadcast threads."),
("pbcast setthreads", 5, "Syntax: .bcast setthreads $num_threads\r\n\r\nChanges number of threads for packet broadcasting."),
("pool list", 5, "Syntax: .pool list\r\n\r\nList of pools with spawn in current map (only work in instances. Non-instanceable maps share pool system state os useless attempt get all pols at all continents."),
("pool update", 5, "Syntax: .pool update $pool_id\r\n\r\nUpdates given $pool_id in current map (possibly adds a new spawn)"),
("pool spawns", 5, "Syntax: .pool spawns $pool_id\r\n\r\nList current creatures/objects listed in pools (or in specific $pool_id) and spawned (added to grid data, not meaning show in world."),
("pool", 5, "Syntax: .pool $pool_id\r\n\r\nPool information and full list creatures/gameobjects included in pool."),
("pdump", 5, ""),
("pdump load", 5, "Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid."),
("pdump write", 5, "Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename."),
("quest", 5, ""),
("quest add", 4, "Syntax: .quest add $quest_id\r\n\r\nAdd to character quest log quest $quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output."),
("quest complete", 4, "Syntax: .quest complete $questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward."),
("quest remove", 4, "Syntax: .quest remove $quest_id\r\n\r\nSet quest $quest_id state to not completed and not active (and remove from active quest list) for selected player."),
("quest status", 2, "Syntax: .quest status $quest_id\r\n\r\nGet quest $quest_id status for target player."),
("reload", 5, ""),
("reload all", 7, "Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded."),
("reload all_area", 5, "Syntax: .reload all_area\r\n\r\nReload all `areatrigger_*` tables if reload support added for this table and this table can be _safe_ reloaded."),
("reload all_eventai", 5, "Syntax: .reload all_eventai\r\n\r\nReload `creature_ai_*` tables if reload support added for these tables and these tables can be _safe_ reloaded."),
("reload all_gossips", 5, ""),
("reload all_item", 5, "Syntax: .reload all_item\r\n\r\nReload `item_required_target`, `page_texts` and `item_enchantment_template` tables."),
("reload all_locales", 5, "Syntax: .reload all_locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded."),
("reload all_loot", 5, "Syntax: .reload all_loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run."),
("reload all_npc", 5, "Syntax: .reload all_npc\r\n\r\nReload `points_of_interest` and `npc_*` tables if reload support added for these tables and these tables can be _safe_ reloaded."),
("reload all_quest", 5, "Syntax: .reload all_quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded."),
("reload all_scripts", 5, "Syntax: .reload all_scripts\r\n\r\nReload `*_scripts` tables."),
("reload all_spell", 5, "Syntax: .reload all_spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded."),
("reload config", 5, "Syntax: .reload config\r\n\r\nReload config settings (by default stored in mangosd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload."),
("reload areatrigger_involvedrelation", 5, "Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table."),
("reload areatrigger_tavern", 5, "Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table."),
("reload areatrigger_teleport", 5, "Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table."),
("reload command", 5, "Syntax: .reload command\nReload command table."),
("reload conditions", 5, ""),
("reload creature", 5, ""),
("reload creature_ai_scripts", 5, ""),
("reload creature_ai_summons", 5, ""),
("reload creature_ai_texts", 5, ""),
("reload creature_battleground", 5, ""),
("reload creature_involvedrelation", 5, "Syntax: .reload creature_involvedrelation\nReload creature_involvedrelation table."),
("reload creature_loot_template", 5, "Syntax: .reload creature_loot_template\nReload creature_loot_template table."),
("reload creature_questrelation", 5, "Syntax: .reload creature_questrelation\nReload creature_questrelation table."),
("reload db_script_string", 5, ""),
("reload disenchant_loot_template", 5, "Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table."),
("reload event_scripts", 5, "Syntax: .reload event_scripts\nReload event_scripts table."),
("reload fishing_loot_template", 5, "Syntax: .reload fishing_loot_template\nReload fishing_loot_template table."),
("reload game_graveyard_zone", 5, "Syntax: .reload game_graveyard_zone\nReload game_graveyard_zone table."),
("reload game_tele", 5, "Syntax: .reload game_tele\nReload game_tele table."),
("reload gameobject", 5, "Syntax: .reload gameobject\nReload gameobject table."),
("reload gameobject_involvedrelation", 5, "Syntax: .reload gameobject_involvedrelation\nReload gameobject_involvedrelation table."),
("reload gameobject_loot_template", 5, "Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table."),
("reload gameobject_questrelation", 5, "Syntax: .reload gameobject_questrelation\nReload gameobject_questrelation table."),
("reload gameobject_scripts", 5, "Syntax: .reload gameobject_scripts\nReload gameobject_scripts table."),
("reload gameobject_battleground", 5, ""),
("reload gossip_menu", 5, "Syntax: .reload gossip_menu\nReload gossip_menu table."),
("reload gossip_menu_option", 5, "Syntax: .reload gossip_menu_option\nReload gossip_menu_option table."),
("reload gossip_scripts", 5, ""),
("reload item_enchantment_template", 5, ""),
("reload item_loot_template", 5, "Syntax: .reload item_loot_template\nReload item_loot_template table."),
("reload item_required_target", 5, ""),
("reload locales_creature", 5, "Syntax: .reload locales_creature\nReload locales_creature table."),
("reload locales_gameobject", 5, "Syntax: .reload locales_gameobject\nReload locales_gameobject table."),
("reload locales_gossip_menu_option", 5, "Syntax: .reload locales_gossip_menu_option\nReload locales_gossip_menu_option table."),
("reload locales_item", 5, "Syntax: .reload locales_item\nReload locales_item table."),
("reload locales_npc_text", 5, "Syntax: .reload locales_npc_text\nReload locales_npc_text table."),
("reload locales_page_text", 5, "Syntax: .reload locales_page_text\nReload locales_page_text table."),
("reload locales_points_of_interest", 5, "Syntax: .reload locales_points_of_interest\nReload locales_point_of_interest table."),
("reload locales_quest", 5, "Syntax: .reload locales_quest\nReload locales_quest table."),
("reload mail_loot_template", 5, "Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table."),
("reload mangos_string", 5, ""),
("reload npc_gossip", 5, ""),
("reload npc_text", 5, ""),
("reload npc_trainer", 5, "Syntax: .reload npc_trainer\nReload npc_trainer table."),
("reload npc_vendor", 5, "Syntax: .reload npc_vendor\nReload npc_vendor table."),
("reload page_text", 5, "Syntax: .reload page_text\nReload page_text table."),
("reload pickpocketing_loot_template", 5, "Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table."),
("reload points_of_interest", 5, "Syntax: .reload points_of_interest\nReload points_of_interest table."),
("reload quest_end_scripts", 5, "Syntax: .reload quest_end_scripts\nReload quest_end_scripts table."),
("reload quest_start_scripts", 5, "Syntax: .reload quest_start_scripts\nReload quest_start_scripts table."),
("reload quest_template", 5, "Syntax: .reload quest_template\nReload quest_template table."),
("reload reference_loot_template", 5, "Syntax: .reload reference_loot_template\nReload reference_loot_template table."),
("reload reserved_name", 5, "Syntax: .reload reserved_name\nReload reserved_name table."),
("reload reputation_reward_rate", 5, ""),
("reload reputation_spillover_template", 5, ""),
("reload skill_discovery_template", 5, "Syntax: .reload skill_discovery_template\nReload skill_discovery_template table."),
("reload skill_extra_item_template", 5, "Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table."),
("reload skill_fishing_base_level", 5, "Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table."),
("reload skinning_loot_template", 5, "Syntax: .reload skinning_loot_template\nReload skinning_loot_template table."),
("reload spell_affect", 5, ""),
("reload spell_area", 5, "Syntax: .reload spell_area\nReload spell_area table."),
("reload spell_bonus_data", 5, "Syntax: .reload spell_bonus_data\nReload spell_bonus_data table."),
("reload spell_chain", 5, ""),
("reload spell_elixir", 5, ""),
("reload spell_learn_spell", 5, "Syntax: .reload spell_learn_spell\nReload spell_learn_spell table."),
("reload spell_pet_auras", 5, "Syntax: .reload spell_pet_auras\nReload spell_pet_auras table."),
("reload spell_proc_event", 5, "Syntax: .reload spell_proc_event\nReload spell_proc_event table."),
("reload spell_proc_item_enchant", 5, ""),
("reload spell_script_target", 5, ""),
("reload spell_scripts", 5, "Syntax: .reload spell_scripts\nReload spell_scripts table."),
("reload spell_target_position", 5, "Syntax: .reload spell_target_position\nReload spell_target_position table."),
("reload spell_threats", 5, "Syntax: .reload spell_threats\nReload spell_threats table."),
("reload spell_disabled", 5, ""),
("reload autobroadcast", 5, ""),
("reload spell_mod", 5, ""),
("reload map_loot_disabled", 5, ""),
("reload cinematic_waypoints", 5, ""),
("reload variables", 5, ""),
("reload spell_group", 5, "Syntax: .reload spell_group\nReload spell_group table."),
("reload spell_group_stack_rules", 5, "Syntax: .reload spell_group\nReload spell_group_stack_rules table."),
("reload creature_groups", 5, ""),
("reload warden", 5, ""),
("reload creature_template", 5, "Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template."),
("reload item_template", 5, ""),
("reload instance_template", 5, ""),
("reload world_template", 5, ""),
("reload gameobject_template", 5, ""),
("reload exploration_basexp", 5, ""),
("reload pet_name_generation", 5, ""),
("reload creature_onkill_reputation", 5, "Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table."),
("reload game_weather", 5, ""),
("reload player_factionchange_reputations", 5, ""),
("reload player_factionchange_spells", 5, ""),
("reload player_factionchange_items", 5, ""),
("reload player_factionchange_quests", 5, ""),
("reload player_factionchange_mounts", 5, ""),
("reload creature_model_info", 5, ""),
("reload nostalrius_string", 5, ""),
("reload cheat_sanctions", 5, ""),
("reload ip_banned", 5, ""),
("reload account_banned", 5, ""),
("reload spamdetector", 5, "Syntax: .reload spamdetector\r\nReload ChatSpam detection rules."),
("reload trashchars", 5, "Syntax: .reload trashchars\r\nReload TrashCharacters detection rules."),
("replay", 5, "Syntax: .replay $filename\r\nRead previously saved packet sequence from specified file."),
("replay record", 4, "Syntax: .replay record $filename\r\nWrite packets send to target to a file."),
("replay forward", 4, "Syntax: .replay forward $timeSecs\r\nWhile playing a saved replay, go forward of $timeSecs seconds."),
("replay stop", 4, "Syntax: .replay stop\r\nStop replay."),
("reset", 6, ""),
("reset honor", 6, "Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character."),
("reset level", 6, "Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost."),
("reset spells", 6, "Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character."),
("reset stats", 6, "Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level."),
("reset talents", 6, "Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player. Playername can be name of offline character."),
("reset all", 255, "Syntax: .reset all spells\r\nSyntax: .reset all talents\r\n\r\n/!\\ Reset les talents OU sorts de TOUS les joueurs /!\\\r\nRequest reset spells or talents at next login each existed character."),
("server", 0, ""),
("server corpses", 5, "Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world."),
("server exit", 6, "Syntax: .server exit\r\n\r\nTerminate mangosd NOW. Exit code 0."),
("server idlerestart cancel", 5, "Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any."),
("server idlerestart ", 5, "Syntax: .server idlerestart $delay\r\n\r\nRestart the server after $delay seconds if no active connections are present (no players). Use $exist_code or 2 as program exist code."),
("server idleshutdown cancel", 5, "Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any."),
("server idleshutdown ", 6, "Syntax: .server shutdown $delay [$exit_code]\r\n\r\nShut the server down after $delay seconds. Use $exit_code or 0 as program exit code."),
("server info", 0, "Syntax: .server info\r\n\r\nDisplay server version and the number of connected players."),
("server log", 5, ""),
("server log filter", 5, "Syntax: .server log filter [($filtername|all) (on|off)]\r\n\r\nShow or set server log filters. If used \"all\" then all filters will be set to on/off state."),
("server log level", 5, "Syntax: .server log level [$level]\r\n\r\nShow or set server log level (0 - errors only, 1 - basic, 2 - detail, 3 - debug)."),
("server motd", 0, "Syntax: .server motd\r\n\r\nShow server Message of the day."),
("server plimit", 6, "Syntax: .server plimit [$num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file"),
("server restart cancel", 3, "Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any."),
("server restart", 5, "Syntax: .server restart $delay\r\n\r\nRestart the server after $delay seconds. Use $exist_code or 2 as program exist code."),
("server shutdown cancel", 3, "Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any."),
("server shutdown", 6, "Syntax: .server shutdown $delay [$exit_code]\r\n\r\nShut the server down after $delay seconds. Use $exit_code or 0 as program exit code."),
("server set", 6, ""),
("server set motd", 6, "Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day."),
("tele add", 3, "Syntax: .tele add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name."),
("tele del", 5, "Syntax: .tele del $name\r\n\r\nRemove location with name $name for .tele command locations list."),
("tele name", 3, "Syntax: .tele name [$playername] $location\r\n\r\nTeleport the given character to a given location. Character can be offline."),
("tele group", 4, "Syntax: .tele group $location\r\n\r\nTeleport a selected player and his group members to a given location."),
("tele", 2, "Syntax: .tele $location\r\n\r\nTeleport player to a given location."),
("trigger active", 5, "Syntax: .trigger active\r\n\r\nShow list of areatriggers wiht activation zone including current character position."),
("trigger near", 5, "Syntax: .trigger near [$distance]\r\n\r\nOutput areatriggers at distance $distance from player. If $distance not provided use 10 as default value."),
("trigger", 5, "Syntax: .trigger [$trigger_id|$trigger_shift-link|$trigger_target_shift-link]\r\n\r\nShow detail infor about areatrigger with id $trigger_id or trigger id associated with shift-link. If areatrigger id or shift-link not provided then selected nearest areatrigger at current map."),
("wp", 5, ""),
("wp show", 5, "Syntax: .wp show [$creature_guid or Select a Creature]\r\non\r\nfirst\r\nlast\r\noff\r\ninfo\r\n\r\nFor using info you have to do first show on and than select a Visual-Waypoint and do the show info!"),
("wp add", 5, "Syntax: .wp add [$creature_guid or Select a Creature]"),
("wp modify", 5, "Syntax: .wp modify [$creature_guid or Select a Creature]\r\nadd - Add a waypoint after the selected visual\r\nwaittime $time\r\nemote ID\r\nspell ID\r\ntext1| text2| text3| text4| text5 <text>\r\nmodel1 ID\r\nmodel2 ID\r\nmove(moves wp to player pos)\r\ndel (deletes the wp)\r\n\r\nOnly one parameter per time!"),
("wp export", 5, "Syntax: .wp export [$creature_guid or Select a Creature] $filename"),
("wp import", 5, "Syntax: .wp import $filename"),
("export", 5, "Export DBC files to database"),
("export spell", 5, ""),
("export effects", 5, ""),
("bot", 6, "Manage bot system"),
("bot add", 6, "Add specified player as a bot ingame."),
("bot add_all", 6, "Load all the bots"),
("bot delete", 6, "Delete one bot"),
("bot info", 6, "Display statistics about bot system."),
("bot reload", 6, "Reload bots configuration."),
("bot stop", 6, "Remove all online bots."),
("bot start", 6, "Enable bot system"),
("bot ranadd", 6, "Add one random bot from table."),
("ahbot", 6, "Manage AH bot"),
("ahbot reload", 6, "Reload AH bot"),
("ahbot update", 6, "Add random items to sell now"),
("world", 6, ""),
("world update", 6, "Syntax: .world update [$worldMask]\r\nDisplay or change target world mask."),
("world cansee", 6, "Syntax: .world cansee\r\nTell if I can see my target, and if my target can see me, regarding our worldmasks."),
("world detail", 6, "Syntax: .world detail\r\nDisplay target worldmask details"),
("possess", 5, ""),
("cinematic", 5, ""),
("cinematic addwp", 5, ""),
("cinematic gotime", 5, ""),
("cinematic listwp", 5, ""),
("escorte", 6, ""),
("escorte create", 6, ""),
("escorte addwp", 6, ""),
("escorte modwp", 6, ""),
("escorte clearwp", 6, ""),
("worldstate", 5, ""),
("worldstate test", 5, ""),
("bg", 5, ""),
("bg status", 5, "Syntax: .bg status\r\nDisplay current battleground status."),
("bg start", 5, "Syntax: .bg start\r\nStart current battleground now."),
("bg stop", 5, "Syntax: .bg stop\r\nInterrupt current battleground."),
("spell", 5, ""),
("spell effects", 5, "Syntax: .spell effects $spellId\r\nDisplay DBC spell effects."),
("spell info", 5, "Syntax: .spell info $spellId\r\nDisplay some DBC spell properties for given spell id."),
("spell search", 5, "Syntax: .spell search $familyName $familyFlags\r\nLook for spells matching given $familyName and $familyFlags."),
("spell iconfix", 6, "Syntax: .spell iconfix $spellid\r\nExclude given $spellid from spell stacking rules concerning SpellIconID. Devs only."),
("variable", 5, "Syntax: .variable $varId [$newValue]\r\nDisplay or set variable $varId value (Database table `variables`)"),
("god", 5, "Syntax: .god [on/off]\r\nEnable or disable god mode: not killable."),
("aura", 4, "Syntax: .aura $spellid\r\n\r\nAdd the aura from spell $spellid to the selected Unit."),
("unaura", 2, "Syntax: .unaura $spellid\r\n\r\nRemove aura due to spell $spellid from the selected Unit."),
("announce", 3, "Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log."),
("notify", 3, "Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen."),
("goname", 2, "Syntax: .goname [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait, e.g. when you are in a group. Character can be offline."),
("namego", 2, "Syntax: .namego [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline."),
("groupgo", 3, "Syntax: .groupgo [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline."),
("commands", 0, "Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level."),
("demorph", 2, "Syntax: .demorph\r\n\r\nDemorph the selected player."),
("die", 3, "Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you."),
("revive", 2, "Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you."),
("dismount", 1, "Syntax: .dismount\r\n\r\nDismount you, if you are mounted."),
("gps", 2, "Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id"),
("guid", 2, "Syntax: .guid\r\n\r\nDisplay the GUID for the selected character."),
("help", 0, "Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands."),
("itemmove", 5, "Syntax: .itemmove $sourceslotid $destinationslotid\r\n\r\nMove an item from slots $sourceslotid to $destinationslotid in your inventory\r\n\r\nNot yet implemented"),
("cooldown", 3, "Syntax: .cooldown [$spell_id]\r\n\r\nRemove all (if spell_id not provided) or $spel_id spell cooldown from selected character or you (if no selection)."),
("unlearn", 3, "Syntax: .unlearn $spell [all]\r\n\r\nUnlearn for selected player a spell $spell.  If \'all\' provided then all ranks unlearned."),
("distance", 2, "Syntax: .distance [$name/$link]\r\n\r\nDisplay the distance from your character to the selected creature/player, or player with name $name, or player/creature/gameobject pointed to shift-link with guid."),
("recall", 2, "Syntax: .recall [$playername]\r\n\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you."),
("save", 1, "Syntax: .save\r\n\r\nSaves your character."),
("saveall", 5, "Saves all online characters."),
("kick", 2, "Syntax: .kick [$charactername]\r\n\r\nKick the given character name from the world. If no character name is provided then the selected player (except for yourself) will be kicked."),
("ban", 3, ""),
("ban warn", 2, "Syntax: .ban warn $name $reason\r\nWarns the selected player."),
("ban account", 3, "Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\"."),
("ban character", 3, "Syntax: .ban character $Name $bantime $reason\r\nBan account and kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\"."),
("ban ip", 3, "Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\"."),
("ban allip", 3, "Syntax: .ban allip $Ip $reason\r\nPermanently bans all accounts on this IP. Ignores accounts with characters over level 10."),
("ban note", 2, "Syntax: .ban note $playerName $reason\r\nAdds a note to the selected player."),
("unban", 4, ""),
("unban account", 4, "Syntax: .unban account $Name\r\nUnban accounts for account name pattern."),
("unban character", 4, "Syntax: .unban character $Name\r\nUnban accounts for character name pattern."),
("unban ip", 4, "Syntax : .unban ip $Ip\r\nUnban accounts for IP pattern."),
("baninfo", 3, ""),
("baninfo account", 1, "Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban."),
("baninfo character", 1, "Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban."),
("baninfo ip", 3, "Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban."),
("banlist", 5, ""),
("banlist account", 5, "Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans."),
("banlist character", 5, "Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required."),
("banlist ip", 5, "Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans."),
("start", 1, "Syntax: .start\r\n\r\nTeleport you to the starting area of your character."),
("taxicheat", 5, "Syntax: .taxicheat on/off\r\n\r\nTemporary grant access or remove to all taxi routes for the selected character. If no character is selected, hide or reveal all routes to you.\r\n\r\nVisited taxi nodes sill accessible after removing access."),
("linkgrave", 5, "Syntax: .linkgrave $graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map)."),
("neargrave", 5, "Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts)."),
("explorecheat", 5, "Syntax: .explorecheat $flag\r\n\r\nReveal  or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\n\r\nUse a $flag of value 1 to reveal, use a $flag value of 0 to hide all maps."),
("hover", 5, "Syntax: .hover $flag\r\n\r\nEnable or disable hover mode for your character.\r\n\r\nUse a $flag of value 1 to enable, use a $flag value of 0 to disable hover."),
("levelup", 5, "Syntax: .levelup [$playername] [$numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by $numberoflevels Or +1 if no $numberoflevels provided). If $numberoflevels is omitted, the level will be increase by 1. If $numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent VALUESrecalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost."),
("showarea", 5, "Syntax: .showarea $areaid\r\n\r\nReveal the area of $areaid to the selected character. If no character is selected, reveal this area to you."),
("hidearea", 5, "Syntax: .hidearea $areaid\r\n\r\nHide the area of $areaid to the selected character. If no character is selected, hide this area to you."),
("additem", 6, "Syntax: .additem $itemid/[$itemname]/shift-click-item-link $itemcount\r\n\r\nAdds the specified number of items of id $itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If $itemcount is omitted, only one item will be added.\r\n."),
("additemset", 6, "Syntax: .additemset $itemsetid\r\n\r\nAdd items from itemset of id $itemsetid to your or selected character inventory. Will add by one example each item from itemset."),
("bank", 2, "Syntax: .bank\r\n\r\nShow your bank inventory."),
("wchange", 4, "Syntax: .wchange $weathertype $status\r\n\r\nSet current weather to $weathertype with an intensity of $status.\r\n\r\n$weathertype can be 1 for rain, 2 for snow, and 3 for sand. $status can be 0 for disabled, and 1 for enabled."),
("ticket", 1, "Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands"),
("ticket assign", 1, "Usage: .ticket assign $ticketid [$gmname].\r\nAssigns the specified ticket to the specified Game Master. If no GM specified, assigns to self."),
("ticket counter", 1, "Usage: .ticket counter $id.\r\nSets current ticket counter."),
("ticket close", 1, "Usage: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently."),
("ticket closedlist", 1, "Displays a list of closed GM tickets."),
("ticket comment", 1, "Usage: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket."),
("ticket complete", 1, "Usage: .ticket complete $ticketid $response.\r\nMarks the ticket as completed. Appends $response to ticket current response."),
("ticket delete", 1, "Usage: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first."),
("ticket escalate", 1, "Usage: .ticket escalate $ticketid.\r\nAdds ticket to escalation queue."),
("ticket escalatedlist", 1, "Usage: .ticket escalatedlist\r\nLists all tickets in escalation queue."),
("ticket list", 1, "Displays a list of open GM tickets."),
("ticket next", 1, "Usage: .ticket next\r\n\r\nDisplays next ticket id."),
("ticket notify", 1, "Usage: .ticket notify [on|off].\r\n\r\nEnables or disables GM ticket notifications."),
("ticket onlinelist", 1, "Displays a list of open GM tickets whose owner is online."),
("ticket previous", 1, "Syntax: .ticket previous\nDisplays previous ticket."),
("ticket reload", 1, "Syntax: .ticket reload $ticketId\nReloads $ticketId from database."),
("ticket reset", 5, "Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing."),
("ticket response reset", 1, "Syntax: .ticket response reset $ticketId\nEmpties the response to ticket $ticketId."),
("ticket response append", 1, "Syntax: .ticket response append $ticketId $response\nAppends $response to the ticket current response (without line break in the end)."),
("ticket response appendln", 1, "Syntax: .ticket response appendln $ticketId $response\nAppends $response to the ticket current response (plus line break in the end)."),
("ticket togglesystem", 4, "Usage: .ticket togglesystem\r\nAllow or disallow players to create tickets."),
("ticket unassign", 1, "Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master."),
("ticket viewid", 1, "Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted."),
("ticket viewname", 1, "Usage: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted."),
("maxskill", 5, "Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum VALUES for its current level."),
("setskill", 5, "Syntax: .setskill $skill $level [$max]\r\n\r\nSet a skill of id $skill with a current skill value of $level and a maximum value of $max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill."),
("whispers", 1, "Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use mangosd.conf setting."),
("pinfo", 2, "Syntax: .pinfo [$player_name]\r\n\r\nOutput account information for selected player or player find by $player_name."),
("respawn", 4, "Syntax: .respawn\r\n\r\nRespawn selected creature or respawn all nearest creatures (if none selected) and GO without waiting respawn time expiration."),
("send", 1, ""),
("send mass", 6, ""),
("send mass items", 6, "Syntax: .send mass items $racemask|$racename|alliance|horde|all \"$subject\" \"$text\" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to players. Subject and mail text must be in \"\". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12."),
("send mass mail", 6, "Syntax: .send mass mail $racemask|$racename|alliance|horde|all \"$subject\" \"$text\"\r\n\r\nSend a mail to players. Subject and mail text must be in \"\"."),
("send mass money", 6, "Syntax: .send mass money $racemask|$racename|alliance|horde|all \"$subject\" \"$text\" $money\r\n\r\nSend mail with money to players. Subject and mail text must be in \"\"."),
("send items", 5, "Syntax: .send items $playername \"$subject\" \"$text\" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12."),
("send mail", 1, "Syntax: .send mail $playername \"$subject\" \"$text\"\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\"."),
("send message", 3, "Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR."),
("send money", 6, "Syntax: .send money $playername \"$subject\" \"$text\" $money\r\n\r\nSend mail with money to a player. Subject and mail text must be in \"\"."),
("loadscripts", 5, "Syntax: .loadscripts $scriptlibraryname\r\n\r\nUnload current and load the script library $scriptlibraryname or reload current if $scriptlibraryname omitted, in case you changed it while the server was running."),
("mute", 2, "Syntax: .mute [$playerName] $timeInMinutes\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline."),
("unmute", 2, "Syntax: .unmute $playerName\r\n\r\nRestore chat messaging for any character from account of character $playerName."),
("movegens", 5, "Syntax: .movegens\r\nShow movement generators stack for selected creature or player."),
("cometome", 5, "come to player"),
("damage", 5, "Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link."),
("combatstop", 2, "Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername."),
("repairitems", 4, "Syntax: .repairitems\r\n\r\nRepair all selected player\'s items."),
("stable", 5, "Syntax: .stable\r\n\r\nShow your pet stable."),
("waterwalk", 5, "Syntax: .waterwalk on/off\r\n\r\nSet on/off waterwalk state for selected player."),
("quit", 5, "Syntax: quit\r\n\r\nClose RA connection. Command must be typed fully (quit)."),
("mmap path", 5, "Syntax: .mmap path [$genStraightPath]\r\nGenerate path between you and your target, and spawn invisible waypoints to see it."),
("mmap loc", 5, "Display your current location on navmesh (tile, polygon, ground flags ...)"),
("mmap loadedtiles", 5, "Display loaded tiles for current map"),
("mmap stats", 5, "Display stats regarding current map navmesh."),
("mmap testarea", 5, "Syntax: .mmap testarea [$radius=40]\r\nTry to generate paths from mobs around you to you."),
("mmap connect", 5, "Connect two points (create an offmesh link)"),
("mmap load", 5, "Load navmesh for current tile."),
("mmap unload", 5, "Unload navmesh for current map"),
("mmap", 5, ""),
("video expendables", 5, "One test command (used for a Naxx trailer)"),
("video turn", 5, "Turn around your target."),
("video", 5, ""),
("freez", 5, "Freeze your target (apply aura 29826). Use .unaura 29826 to unfreeze."),
("anticheat", 3, ""),
("anticheat behavior", 3, "Syntax: .anticheat behavior $playername\r\nDisplay computed behavior values for given $playername."),
("anticheat behavior search", 4, "Syntax: .anticheat behavior search $searchQuery\r\nSearch online players with behavior values that match query. Query format example: \"5>2 3<2\" (value 6 > 2 AND value 3 < 2)"),
("anticheat client", 6, "Syntax: .anticheat client [$playername]\r\nGive client unique hash computed by the warden."),
("anticheat client hook", 6, "Syntax: .anticheat client hook $hash\r\nGet an alert when a client with the given hash logs in."),
("anticheat client find", 6, "Syntax: .anticheat client find $find\r\nFind clients with given hash from connected players."),
("anticheat mark", 3, "Syntax: .anticheat mark $playername reason\r\nMark $playername as unwanted players (cheater / botter / exploiter) for given reason. These datas will be used to train the anticheat system to recognize specific behaviors."),
("anticheat scan", 3, "Syntax: .anticheat scan\r\nEnables periodic scan for potentially unwanted players. Disconnect to remove."),
("anticheat server", 2, "Syntax: .anticheat server [$playername]\r\nDisplay Anticheat (server side) information for target or given player name."),
("anticheat warden", 6, "Syntax: .anticheat warden [$playername]\r\nDisplay Warden (client side) information for target or given player name."),
("anticheat warden read", 6, "Syntax: .anticheat warden read $address [$length]\r\nAttempts to read $length bytes in the target's memory at given $address."),
("anticheat warden addons", 6, "Syntax: .anticheat warden addons\r\nDisplays detected Addons on target"),
("groupspell", 5, ""),
("groupspell add", 5, ""),
("groupspell rule", 5, ""),
("runtest", 5, "Syntax: .runtest [$testNamePart]\r\nRun tests containing $testNamePart in their name (or all available tests)."),
("log", 1, "Syntax: .log $id\r\nDisplays content of log $id.");

UPDATE command SET flags = 1, security = 2 WHERE name="instance unbind";
